### ISSUE TITLE
Create a new project for consuming data with Javascript

### ISSUE THREAD

**Issue by mortenson** [contentacms/contenta_jsonapi#103]
Looking at the example consumers for this project, there have been a few attempts at parsing JSON API data coming from contenta_jsonapi:

1. In [contentacms/contenta_vue_nuxt](https://github.com/contentacms/contenta_vue_nuxt), a [new service was created](https://github.com/contentacms/contenta_vue_nuxt/blob/79a23daa3c4783fcb5a6534a89045414f398f387/services/D8JSONAPIClient.js) using [d8-jsonapi-querystring](https://www.npmjs.com/package/d8-jsonapi-querystring) and [jsonapi-parse](https://www.npmjs.com/package/jsonapi-parse) packages. This allows you to generically query JSON API data, using a well-structured query object.
1. In [contentacms/contenta_angular](https://github.com/contentacms/contenta_angular), a [new service was created](https://github.com/contentacms/contenta_angular/blob/7588de65fa0d228fc787e9867628c5ec808922a3/src/app/components/recipe/services/recipe.service.ts) using [ngrx/store](https://github.com/ngrx/store). This allows you to query for recipes abstractly and parse the JSON API response into recipe models, and change the app state when recipes are loaded.
1. In [contentacms/contenta_react](https://github.com/contentacms/contenta_react), a [new Redux action was created](https://github.com/contentacms/contenta_react/blob/e0bfa0aaa929790e4959f6f8d1bd73001139f47d/src/actions/api.js) to make/parse a recipe response and dispatch [another action to load the front page](https://github.com/contentacms/contenta_react/blob/f3f8d580dd5c0d60fb17b454b04a13fe13c70ac9/src/reducers/api.js).
1. In [contentacms/contenta_ionic](https://github.com/contentacms/contenta_ionic), a [new service was created](https://github.com/contentacms/contenta_ionic/blob/master/src/services/datastore.service.ts) using [angular2-jsonapi](https://github.com/ghidoz/angular2-jsonapi) to abstractly query models from JSON API that are [defined by their attributes and endpoint](https://github.com/contentacms/contenta_ionic/tree/master/src/models). These attributes can also define relationships to other models, which angular2-jsonapi will parse automatically from the JSON API "relationships" object. angular2-jsonapi is, unfortunately, not maintained anymore.

The various consumers are welcome to query JSON API data in any way they choose - but what do we recommend for developers starting new projects with Contenta?

I propose that we create a new project either documenting best practices for making requests to Contenta, or providing a generic service that everyone can use.

Here are some example requirements for a consumer-solution, which we can discuss and redefine here:

1. Can use query objects instead of concatenating query strings
1. Supports authentication methods provided by Contenta
1. Handles sub-requests (both sending and receiving them)
1. Allows (but not requires) users to model data and not query Contenta directly with HTTP. i.e. something like `recipe.save()` or `recipe.image.uri` should be possible.
1. Works with all frameworks/libraries, so that existing state handling in consumers could still happen. Alternatively we can write multiple docs/services.
1. Implements or documents client-side cache, to support offline-first implementations.

**Comment by mortenson** [comment]
On [Twitter](https://twitter.com/AlwaysWorking/status/882287321067823105) @mattgrill mentioned that [waterwheel.js already has JSON API support](https://github.com/acquia/waterwheel.js#json-api), and is planning to support sub-requests.

**Comment by yann-yinn** [comment]
I did not try waterwheel with contenta : I thought it was only working with core REST module and not JSON API standard. Maybe we should start here ...
Waterwheel seems to work with _axios_ http request library, which is a good thing for vuejs + nuxtjs,  as it works both on Server Side Rendering and the browser.

**Comment by mortenson** [comment]
I filed https://github.com/acquia/waterwheel.js/issues/60 to potentially add resource modeling to Waterwheel

**Comment by yann-yinn** [comment]
I'm currently switching to waterwheel instead of "_d8-jsonapi-querystring_" npm package on contenta_vue_nuxt.  I keep using "_jsonapi-parse_" npm package to resolve relationships / included objects.

**Comment by e0ipso** [comment]
Would it make sense to move the parser into waterwheel?

**Comment by mortenson** [comment]
I mentioned it in https://github.com/acquia/waterwheel.js/issues/60, it would be a good first step to get everyone using it.

**Comment by yann-yinn** [comment]
I did the full switch now, works very well : https://contentavuedemo.github.io/
Would recommend waterwheel to beginners because of its authentication support (did not try it yet)
Works well from Browser AND server-side , perfect for me.

**Comment by e0ipso** [comment]
That looks like a nice resolution.
