### ISSUE TITLE
Create a docker image for this distribution

### ISSUE THREAD

**Issue by mortenson** [contentacms/contenta_jsonapi#106]
It would be useful to have a docker image for contenta_jsonapi, to make sure that we're all on similar dev environments. There have been a few issues reported in Slack that are related to incompatible Drush/PHP versions, which wouldn't be a problem if everyone was using docker.

Additionally, a docker image could also include all the example consumers, which would be a great way to get newcomers excited about the project. i.e. localhost:8888 would be Drupal, but localhost:8888/consumer/ionic would be the contentacms/contenta_ionic project, already configured to connect to localhost:8888/api.

Caveats:

1. Building and running docker will always be slower than just using composer and "drush run-server".
1. Docker has known performance issues with Mac OS X, which should be resolved soon but are a concern. I _think_ that Drupal VM overcomes these speed issues and generally has the best Drupal docker setup out there.

**Comment by e0ipso** [comment]
Are you familiar with https://github.com/contentacms/contenta_docker? It seems that @pcambra and @cjgratacos are thinking in similar terms and you could collaborate!

Let me know if you want to be added to that team.

**Comment by mortenson** [comment]
I had no idea! I'll file a PR with the consumers if I get some time, but this can be closed out.

**Comment by dawehner** [comment]
Well, swapping out quick install to use the docker image would be worth a discussion still, IMHO.
