### ISSUE TITLE
Consider pre-configuring config split

### ISSUE THREAD

**Issue by greg-1-anderson** [contentacms/contenta_jsonapi#110]
I love the default content provided by Contenta. With the [config split](https://www.advomatic.com/blog/using-configuration-split-to-have-dev-only-configuration-in-drupal-8) module, it would be possible to have the default content disabled in the live environment, but have it come back in development environments, even after pulling down the live database.

Just a thought; haven't tried it yet.

**Comment by greg-1-anderson** [comment]
Not so relevant. Closing.

**Comment by dawehner** [comment]
I was wondering whether we could also use a migrate revert for this
particular functionality / removing live content

**Comment by greg-1-anderson** [comment]
In my experience, migrate revert did work fine after successful migrations, but I tended not to use it, as it did not always behave well if I fed garbage into the import process. For example data, which will presumably always import cleanly, it should be an option. Relying on install / uninstall of the module as it currently is also seems to be convenient enough.
