### ISSUE TITLE
Curl example in the documentation

### ISSUE THREAD

**Issue by greg-1-anderson** [contentacms/contenta_jsonapi#111]
There is a lot of documentation on Contenta and the jsonapi; however, I am still having trouble getting a basic `curl` command to retrieve data from the example content.

Per [Fetching resources ](https://www.drupal.org/docs/8/modules/json-api/fetching-resources-get) in the jsonapi documentation, I tried:
```
curl --header 'Accept: application/vnd.api+json' http://SITE/jsonapi/node/recipes/61
```
and
```
curl --header 'Accept: application/vnd.api+json' http://SITE/jsonapi/api/recipes/61
```
This results in a 404, even though I can view http://SITE/node/61 as an anonymous user with no trouble. The documentation says that GETs should work unauthenticated for resources that do not require authentication.

According to the [client responsibilities](http://jsonapi.org/format/#content-negotiation-clients) section of the documentation jsonapi.org, clients need to set the content type:
```
Clients MUST send all JSON API data in request documents with the header Content-Type: application/vnd.api+json without any media type parameters.
```
However, trying different combinations of Content-Type &/or Accept headers did not change my result.

Running `drupal router:debug` showed routes such as `/api/recipes/{node}`, but removing the `jsonapi` from the request URL did not work either.

The online schema API documentation available within a Contenta install is very cool, but it did not help clarify the above. In fact, it's a little more confusing, as the `individual get` entry for the Recipe content shows `GET /api/recipes/{node}` in the right margin, but the expanded view shows the server URL to be `http://SITE/jsonapi/api/recipes/{node}`. It seems like the server URL is what should be used with Curl et. al., but again, this does not work.

Could someone please clarify which documentation is applicable to the components used with Contenta, and how to map the information in this documentation to working `curl` commands? It's not clear to me what I am doing wrong.

**Comment by dawehner** [comment]
Note 1: you now longer need the accept header
Note2: jsonapi accepts a uuid, not an entity id

**Comment by e0ipso** [comment]
You can also drop the ID altogether and you'll get a list of recipes instead.

**Comment by greg-1-anderson** [comment]
Tried:
```
curl http://STIE/jsonapi/api/recipes
```
Got a 404 in HTML. With the accept header, I got a 404 in json.

I'll go look up an entity ID and see if I can get a single entity back. Thanks for the pointer on that.

**Comment by dawehner** [comment]
It should be host:port/API/recipes

**Comment by greg-1-anderson** [comment]
Ah that did the trick! Never tried the permutation of removing `jsonapi` and omitting the node ID. Now that I know to use the UUID and leave off the `jsonapi`, it is working.

Thanks!

**Comment by greg-1-anderson** [comment]
Just to close the loop on this issue, where are the documentation bugs that should be corrected?

For example, is [Fetching resources ](https://www.drupal.org/docs/8/modules/json-api/fetching-resources-get) in any way wrong, or did Contenta configure the module to change the default routes?

Also, what is the explanation for the server url in the online generated documentation? Is a request to the schemata module in order here?

Where is the best place to stipulate that the needed ID is a uuid, not an entity ID? The [jsonapi examples](http://jsonapi.org/format/#document-compound-documents) imply entity IDs. Is this just out-of-date, or is it something Contenta configured to behave differently?

I could submit a documentation PR if I had a good understanding of the source of the current confusion, and how to make it better.

**Comment by e0ipso** [comment]
> For example, is Fetching resources in any way wrong, or did Contenta configure the module to change the default routes?

Contenta uses JSON API to customize the API in order to remove many of the Drupalisms.

> Also, what is the explanation for the server url in the online generated documentation? Is a request to the schemata module in order here?

We need to better expose this one. In fact I just [created an issue to do so](https://github.com/contentacms/contenta_jsonapi/issues/112). It's in `/admin/config/services/openapi/redoc/jsonapi`.

> Where is the best place to stipulate that the needed ID is a uuid, not an entity ID? The jsonapi examples imply entity IDs. Is this just out-of-date, or is it something Contenta configured to behave differently?

That is the specification's documentation. There is no restriction in what the implementing servers use as UUID. The JSON API maintainers decided for a UUID a while back. It should be already documented in [Fetching resources](https://www.drupal.org/docs/8/modules/json-api/fetching-resources-get). It seems obvious that it's not super clear though.

**Comment by greg-1-anderson** [comment]
I added a sentence to the top of Fetching resources to be explicit about uuid vs entity id:

> Note that in all cases, when an id is needed, it is always the entity's uuid, not the entity id.

The examples on that page clearly used {{article_uuid}} et. al., but since it never explicitly said "entity uuid", it was a little confusing to me -- especially since other sources had examples with small integers (which could be entity ids, but could not be entity uuids). I'll try to also track down and correct these examples.

**Comment by e0ipso** [comment]
Having comprehensive documentation is very difficult. It is indeed a community effort. Thanks for closing the loop here Greg!

**Comment by greg-1-anderson** [comment]
Oh, I see now. I was confused by http://jsonapi.org/format/#document-compound-documents, but the examples here are completely generic, and not Drupal specific. The Drupal implementation picked entity uuids for ids, so the generic documentation isn't completely in alignment.

The one thing I'm still confused about is the fact that the Drupal JSON API documentation says that URLs start with "jsonapi", but in Conenta it's "api". Is this something that is done by the JSON API Extras module? Is this configurable, or done implicitly whenever the module is enabled?

**EDIT:** Found it! /admin/config/services/jsonapi/settings

This behavior change should be documented somewhere in the Contenta documentation, but I'm not sure where yet.

**Comment by greg-1-anderson** [comment]
Maybe a Curl frontend might be helpful? Could link to it in the example frontends on the http://www.contentacms.org/ if it existed. Or maybe link to the [JSON API CLI](https://github.com/consolidation/json-api-cli), when it's complete enough to do something. (Currently works for unauthenticated data fetch only).

**EDIT:** Rather than an example frontend, I instead suggested in #115 that perhaps the README could have a simple Curl example, to help get people started with direct use of the jsonapi.

**Comment by greg-1-anderson** [comment]
And finally, the page /admin/config/services/openapi/redoc/jsonapi#tag/Content-Recipe is confusing, because the [openapi module](https://www.drupal.org/project/openapi) does not correctly reflect the API prefix modification done by the JSON API Extras module.

Should the JSON API extras be hooking this module to change this entry, or is this a bug in the openapi module, not correctly querying for the correct base URL when generating this URL?
