### ISSUE TITLE
Allow access to Open API documentation easily

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#112]
We need to:

  - [x] Provide the default permissions so users with the `client_developer` role can access the ducumentation.
  - [x] Provide an alias for `/admin/config/services/openapi/redoc/jsonapi` under `/openapi`.

This will need to be integrated with the efforts in: #59.

**Comment by dawehner** [comment]
I think putting it into the menu/toolbar should be part of it as well.

**Comment by e0ipso** [comment]
This was done.
