### ISSUE TITLE
Remove node_modules from the release artifact

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#117]
It's about 38Mb that we can shave since it is only for testing purposes.

**Comment by dawehner** [comment]
Note: We should also execute

```
"post-package-install":
"Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup",
        "post-package-update":
"Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup"
```


inside our composer.json as well, as this probably saves quite a bit of
code as well.

Mateu Aguiló Bosch <notifications@github.com> schrieb am Mo., 10. Juli 2017
um 21:09 Uhr:

**Comment by cjgratacos** [comment]
Sounds good, @e0ipso and @dawehner, will work on it.

**Comment by cjgratacos** [comment]
@e0ipso @dawehner, what are your opinions on leaving the contenta_jsonapi profile folder as clean as possible for the release artifact?
With this I mean only leaving CHANGELOG.md, CODE_OF_CONDUCT.md, composer.json, config, LICENSE.txt,modules, scripts, themes and README.md.

**Comment by e0ipso** [comment]
The main goal for this release artifact is to be installable by drush
without further downloading.

**Comment by cjgratacos** [comment]
👍  perfect, pack the least we need

**Comment by e0ipso** [comment]
Also, during the migration that happens on site install (which happens for
the tests anyways), we download many images. We will need those recipe
images in the release ZIP as well.



[image: --]

Mateu Aguiló Bosch
[image: https://]about.me/e0ipso
<https://about.me/e0ipso?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
