### ISSUE TITLE
Integrate with readthedocs

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#120]
After #119 was merged we have a `docs/` folder with `*.md` files. That means that we can leverage http://readthedocs.org

In particular we may want to integrate like this https://docs.readthedocs.io/en/latest/builds.html#mkdocs

**Comment by cjgratacos** [comment]
Closing this issue. Integration was done

_Sent from my Lge LG-H918 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dawehner** [comment]
<3

Carlos Gratacos <notifications@github.com> schrieb am Mo., 17. Juli 2017 um
13:14 Uhr:
