### ISSUE TITLE
Installation with acquia dev desktop

### ISSUE THREAD

**Issue by arifkhn46** [contentacms/contenta_jsonapi#122]
Hi Guys,

I am trying to install contenta on acquia dev desktop but I am facing an issue. The issue is I am trying to import the contenta as drupal project in the acquia desktop but when I am selecting the contenta folder to import, the acquia dev desktop is showing an alert, which says chosen directory is not a durpal site. Please refer the attachment for more details.

Please help!

![contenta-add](https://user-images.githubusercontent.com/12694008/28160164-33ce174a-6774-11e7-93e2-acae04358ae6.PNG)

**Comment by dawehner** [comment]
Do you mind explaining a bit more how you actually downloaded contenta?

I have the feeling you downloaded this git repo directly. In this case, read more on https://github.com/contentacms/contenta_jsonapi#installation-for-building-your-own-site

**Comment by e0ipso** [comment]
Maybe worth noting that you will need to point the root of your install to `…\contentacms\web`.

**Comment by arifkhn46** [comment]
@dawehner I downloaded the contenta using composer first then I am trying to import it in ADD.

@e0ipso I am new to ADD I think I need to search about it.
