### ISSUE TITLE
Installation error: Drupal\Core\Config\UnmetDependenciesException: 

### ISSUE THREAD

**Issue by arifkhn46** [contentacms/contenta_jsonapi#123]
Environment:
OS: Windows
Server: Acquia Dev Desktop

Installation steps:
1) I used composer to download the contenta setup
   composer create-project contentacms/contenta-jsonapi-project MYPROJECT --stability dev --no-interaction
2) Place the contenta setup in the Acquia Dev Desktop's root folder.
3) Import the project locally into Acquia Dev Desktop.
4) open the project in the browser and run through the installation process
5) Finally at last after filling the site information I got the error.

PFA of error occurred during installation:

![installation-error](https://user-images.githubusercontent.com/12694008/28168534-4196fc78-6794-11e7-8a08-7714284c58d4.PNG)

**Comment by cmoeser** [comment]
Experiencing the same issue 9/3 when trying to install via composer.
Windows 8
IIS 6.2
MySQL 6.2

**Comment by e0ipso** [comment]
I don't think this is an issue anymore. Please request a re-open if this is the case.
