### ISSUE TITLE
Don't require "webflo/drupal-core-strict".

### ISSUE THREAD

**Issue by Jaesin** [contentacms/contenta_jsonapi#124]
Some of us like to lock into tested version but others don't so we shouldn't force users to a specific version of dependencies.

Also, the required version is hard coded to 8.3.4 and 8.3.5 is out now.

**Comment by dawehner** [comment]
Conceptually I think drupal-core-strict is nice for actual problems, but I see the point.

What about moving it from contenta_jsonapi to contenta_jsonapi_project, so its nicely adaptable per project?

**Comment by dawehner** [comment]
We fixed that in the meantime. Yeah!
