### ISSUE TITLE
Broken links when installed in subdir

### ISSUE THREAD

**Issue by NikLP** [contentacms/contenta_jsonapi#127]
I'm not sure if there's a failure to use best practises here or what, but I have this installed in a subdirectory and all the links are broken. Seemingly this is because they start with a forward slash, which assumes site root == domain root, which is a bit of an arrogant (and incorrect) supposition if you don't mind me saying. This is obviously super annoying, and there's no way to correct it without moving the site to a domain root, which is more annoying...

**Comment by dawehner** [comment]
I agree we should try to fix the links, just like Drupal does in general. Thank you for the report.

I assume your try out contenta locally.

The short time workaround is: Use ```drush run-server```, it will use its own port, so you don't need to worry about anything.

**Comment by NikLP** [comment]
No I've got it running in a dev account on my linode, in which I have several subdirs for testing. So it's kind of a "proper" install, but it's irrelevant really. I think as you say the links are what need fixing if possible. :)

**Comment by dawehner** [comment]
Thank you @NikLP this makes sense.
As far as I see we would need to ship with the pathologic module for that.
Thoughts?

**Comment by NikLP** [comment]
I thought settings $base_url and then using paths like "this" instead of "/this" would fix it, but I've had no end of trouble setting base paths in D8 and indeed am using Pathologic in my previous build which has no problems of this nature (IIRC!!)

Furthermore I found this Yoast article (2012) which seemingly avidly promotes such a method. 
https://yoast.com/dev-blog/relative-urls-issues/

**Comment by e0ipso** [comment]
I'm leaning towards closing this one. This is a common problem with subdir installs in Drupal, not necessarily a Contenta issue.

Please, request a reopen if you think that Contenta should include pathologic by default to avoid this.

**Comment by dawehner** [comment]
At least Drupal core itself is 100% compatible, given that all its tests
are actually executed against a subdir installation.

Mateu Aguiló Bosch <notifications@github.com> schrieb am Di., 7. Nov. 2017
um 22:09 Uhr:
