### ISSUE TITLE
Make it clear in the UI that the main content of contenta requires a logged in user

### ISSUE THREAD

**Issue by dawehner** [contentacms/contenta_jsonapi#131]
Currently its not really clear that the user most probably needs to login to get anything good out of it.

* Any ideas how to fix that? Maybe we could move to login link more prominent.
* Maybe we could display a message: Please log in ...

**Comment by e0ipso** [comment]
This is probably the job of the welcome page.

**Comment by e0ipso** [comment]
This was done.
