### ISSUE TITLE
Assets vs. Media naming

### ISSUE THREAD

**Issue by dawehner** [contentacms/contenta_jsonapi#132]
Currently there is a mismatch between using the word _Assets_ and _Media_ in several places:

![screen shot 2017-07-15 at 22 00 58](https://user-images.githubusercontent.com/29678/28242649-28cf2ed8-69a9-11e7-88fe-d1e87059ad08.jpg)

* [x] Agree with to a common naming
* [x] Use it in as many places as possible

**Comment by e0ipso** [comment]
I recall you proposed _Assets_ in the past? I'm good with that.

**Comment by dawehner** [comment]
Given that all the documentation about media in Drupal is using "Media" as term, I'm not sure about it anymore

**Comment by e0ipso** [comment]
Good point. Let's use _media_ then.

**Comment by e0ipso** [comment]
This is addressed in #145 moving conversation there.
