### ISSUE TITLE
Minimize the vertical space

### ISSUE THREAD

**Issue by dawehner** [contentacms/contenta_jsonapi#134]
A lot of the vertical space of the admin pages is filled up with meta content, not the content of the current page, see screenshot:

![screen shot 2017-07-15 at 22 15 19](https://user-images.githubusercontent.com/29678/28242720-2e0796a4-69ab-11e7-87a8-e20f4778f5c2.jpg)

It would be nice if we could do something about it:

* Drop the breadcrumb?
* Move the title somewhere else?

**Comment by e0ipso** [comment]
Paging @bcwald for this one.

**Comment by NikLP** [comment]
I have a big problem with this, and I have to say I think the Materialize (/Admin) themes are to blame. They're simply too "big". I am sitting by a 12" X220 and I have what I would call "two business objects" on screen - really maybe only one. While these themes might follow the Material design process, they simply don't feel right for this project IMO, there's way WAY too much whitespace.
See ![matadtheme](https://user-images.githubusercontent.com/2248659/28491011-ff6e18ba-6edf-11e7-837c-9a71bc007696.png)

**Comment by e0ipso** [comment]
> . While these themes might follow the Material design process, they simply don't feel right for this project IMO

Can you elaborate on that?

**Comment by NikLP** [comment]
Because of the whitespace! This project is predominantly about data input and content listings, both of which require "all the things on the screen" and there's just nothing meaningful on mine...

**Comment by e0ipso** [comment]
> I am sitting by a 12" X220 and I have

I'm not familiar with that device. Is that a tablet? In any case I think a screen that small will always fit less items. Have you tried in other devices?

**Comment by e0ipso** [comment]
> Because of the whitespace!

I'll let the experts speak about this, but I think the white space is important for touch devices.

**Comment by NikLP** [comment]
It's a 12" laptop, with same resolution as most other screens of about 12/13.3/14 inches. Attached screenshot shows ONE meaningful line of content on screen. It's not right.

**Comment by dawehner** [comment]
I'm wondering whether we could leverage the layout component, see https://getmdl.io/components/#layout-section/layout

**Comment by e0ipso** [comment]
I think we'll stick with what Material Admin has to offer. There are other benefits we are getting from it.
