### ISSUE TITLE
Uninstall the experimental datetime range module

### ISSUE THREAD

**Issue by dawehner** [contentacms/contenta_jsonapi#135]
We should consider uninstalling the datetime range module until its marke as stable

* In case the data model would change, we would screw up a lot of users data
* It is shown on the status report page as warning

**Comment by cjgratacos** [comment]
@dawehner That is actually a good idea. Is the datetime range module is on alpha, beta, eap?

**Comment by dawehner** [comment]
I think its in beta right now.

**Comment by budda** [comment]
Datetime range module now part of 8.4 as a stable but experimental release.
https://www.drupal.org/node/2893128#comment-12176768

is this now a non-issue?

**Comment by dawehner** [comment]
I would say so?
@budda In general do you want to try updating contenta to 8.4? This would be amazing!

**Comment by budda** [comment]
Hah - nice delegation 😄

I've heard of the pains moving to Drupal 8.I over the past week. Not sure
I'm ready for it just yet.

**Comment by budda** [comment]
Hah - nice delegation 😄

I've heard of the pains moving to Drupal 8.4 over the past week. Not sure
I'm ready for it just yet.

**Comment by e0ipso** [comment]
This was a non-issue after all, as @dawehner predicted.
