### ISSUE TITLE
Use a leaner testing framework

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#138]
We are having several issues that could be mitigated by removing the dependency on Nightwatch:

  * Build time. It takes longer than necessary to test every PR because we need to install a node.js environment (parallel to the PHP one) in Travis. The builds are taking an average of 14-30 min.
  * Build size. It doubles the size of the release artifact. I assume it's the binaries for the browsers. Requiring ad-hoc fixes like: https://github.com/contentacms/contenta_jsonapi/pull/136
  * It uses browser testing for an API-First project. I don't think that Nightwatch is the right tool for this particular scenario.

**Comment by e0ipso** [comment]
My proposal is to use the tools that we already have available in Drupal to do the _healthcheck_ test that the current Nightwatch setup is doing. A functional test in Drupal will do the job.

In the future we can easily test the API by using Guzzle in functional tests.

Thoughts or proposals?

**Comment by cjgratacos** [comment]
I do agree with the idea, making the ci faster. Guzzle will suffice and make the job for at least the API Testing, aka the Functional part. Will make it leaner and that is what we want.

IMHO, we should also start thinking about having more coverage in other levels of testing and start leveraging PHP testing framework like codeception or other.

_Sent from my Lge LG-H918 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by e0ipso** [comment]
A first (in progress) attempt is in https://github.com/contentacms/contenta_jsonapi/pull/159.

**Comment by cjgratacos** [comment]
Working on it

**Comment by dawehner** [comment]
At least for me point 1) and point 2) are quite week, but yeah we probably don't need to test user interfaces right now. ... In case we do though, I think nightwatch is a better tool than what we have to offer on the PHP site.

**Comment by e0ipso** [comment]
All in agreement I think.

I agree that Nightwatch is better than the PHP-only equivalent. However in order to test APIs we don't need a browser, in fact we should avoid a browser.

**Comment by dawehner** [comment]
I agree that using a browser for APIs is weird. I'm wondering whether we
can keep nightwatch and use it for testing the API docs UI, which is IMHO
by far the most important one we have. Personally I would love to keep
nightwatch around to collect experience for further usage in core. What do
you think about this compromise?

* I had a look at the build times, and it seems to mostly general stuff
which is slow. The NVM use is basically instant
* I agree with the build size, but we can ignore all the node_modules in
there, can't we?


Mateu Aguiló Bosch <notifications@github.com> schrieb am Mi., 9. Aug. 2017
um 15:34 Uhr:

**Comment by e0ipso** [comment]
Closed in favor of https://github.com/contentacms/contenta_jsonapi/pull/164
