### ISSUE TITLE
Improve configuration export workflow

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#14]
See Slack discussion: https://drupal.slack.com/archives/C5A70F7D1/p1495575161979991

![slack - drupal 2017-05-23 23-40-05](https://cloud.githubusercontent.com/assets/1140906/26377587/2e459706-4011-11e7-9346-2cb348632cb5.png)

**Comment by dawehner** [comment]
I hope I'll find a bit of time to talk with @alexpott about it

**Comment by e0ipso** [comment]
This is implemented. I'm using the following command to exclude config (as stated in 3.5):

```shell
for deletable in $(for name in $(find config/sync | xargs basename); do find ../test_contenta_jsonapi/web/modules/contrib/recipes_magazin/config/install/$name | xargs basename; done 2>&1 | grep -v 'No such file or directory'); do rm config/sync/$deletable; done
```

It's rudimentary, but it works.

**Comment by dawehner** [comment]
Can we out that in a composer script?

**Comment by e0ipso** [comment]
@dawehner we'd need to get fancy for the Contenta folder and the installed site folder. But we can leave this open for now.

**Comment by dawehner** [comment]
Maintaing config is hard

**Comment by e0ipso** [comment]
This is the shell script I'm using nowadays:

```shell
# Find the config already in the features, and move it there.
for module in $(ls modules); do
  for name in $(find modules/$module/config/install -name "*.yml" -exec basename {} \;); do
    mv config/sync/$name modules/$module/config/install/$name;
  done;
done;
```
