### ISSUE TITLE
Don't install require-dev dependencies on the release artifact

### ISSUE THREAD

**Issue by cjgratacos** [contentacms/contenta_jsonapi#149]
Currently, in the release artifact, we are bundling the project's require-dev dependencies specified in composer.json.

Such dependencies are unnecessary to be bundled in a release. 

This will reduce the release artifact's size, and reduce deployment time.

**Comment by dawehner** [comment]
Nice idea!

Carlos Gratacos <notifications@github.com> schrieb am Di., 18. Juli 2017 um
16:19 Uhr:

**Comment by e0ipso** [comment]
@cjgratacos is this a good candidate for the `help wanted` label?

**Comment by e0ipso** [comment]
@cjgratacos was this worked on? I'd like to revisit this.
