### ISSUE TITLE
Add an API version number to the response

### ISSUE THREAD

**Issue by justafish** [contentacms/contenta_jsonapi#158]
I know that being able to serve two different versions of the API from the same site is really hard because of content model changes, but a string in the header saying which version of the API is currently active would be really useful. This way I could build a consumer to support both APIs simultaneously if there's a major change in the API pending (using a dev server to test the new API and production for the old one for example)

I don't know if it's possible to auto-bump the number on deploy if there's any content model or JSON:API configuration changes, but that would be nice, e.g. bump a major version if there's any changes to content type yaml files which affect field names

**Comment by e0ipso** [comment]
Would this be something that is maintained manually? Maybe just a config option that is exposed in API responses?

**Comment by e0ipso** [comment]
I think that this could be implemented fairly easily with a response subscriber.

**Comment by wimleers** [comment]
Related: https://www.drupal.org/node/2813311

**Comment by dawehner** [comment]
@justafish @e0ipso  @wimleers 
What do you think is the right project to add these hard coded API numbers? It could be for example jsonapi_extras ... but it feels like contenta is not only the easier option, its also the place which has enough business knowledge to make reasonable API versioning number decisions.

**Comment by e0ipso** [comment]
Maybe the API version could be a substring of an MD5 of the site configuration. While everything stays the same, the version stays the same.

To make it fancier we could have some sort of exclude logic that uses site-level information to avoid unnecessary version bumps.

**Comment by dawehner** [comment]
What about just taking into account entity/field/jsonapi configuration?

**Comment by e0ipso** [comment]
I think that many things can potentially come into play that are hard to anticipate: image styles, text formatters, …

But if we can pin it down to a fixed set, that is even better.

**Comment by dawehner** [comment]
As first step its indeed sufficient to use a sha256 hash of all the
configuration.

Mateu Aguiló Bosch <notifications@github.com> schrieb am Mi., 9. Aug. 2017
um 16:20 Uhr:

**Comment by justafish** [comment]
A number is preferable, because I can't do comparisons on md5 hashes in my consumer. I can't say "if version is less than x, do this API call, otherwise do y"

**Comment by e0ipso** [comment]
The idea would be to use the hash to automatically increment the version number if said hash is different than the previous one.

**Comment by justafish** [comment]
sounds good! 👍

**Comment by e0ipso** [comment]
After DrupalCon Nashville we decided on a slightly different approach to versioning in Drupal core.
