### ISSUE TITLE
Production (performant) vs. development settings

### ISSUE THREAD

**Issue by dawehner** [contentacms/contenta_jsonapi#16]
Drupal core (standard profile), decided to provide as performant as possible configuration by default.

This includes

* Disabling showing of error messages
* some more

The underlying question though is: Do we want to follow the same route of having production settings by default?

**Comment by e0ipso** [comment]
I would rather go with DX over production ready out of the box. We should enable errors by default.

Any other setting you'd like to change?

**Comment by dawehner** [comment]
For me this was mostly about policy/general direction.

For a sec. I thought about the typical contestants like CSS / JS aggregation, but then I realized, these don't matter for a decoupled approach.

* Memory only caching for migrations

**Comment by e0ipso** [comment]
I think this was done, right? Can you close this if fixed?

**Comment by dawehner** [comment]
True. We just need to keep it in mind when making decisions
