### ISSUE TITLE
Wrong Server URLs in /admin/api

### ISSUE THREAD

**Issue by mdonadio** [contentacms/contenta_jsonapi#160]
I am seeing two problems with the Server URLs for the endpoints listed in the `admin/api` path:

<img src="https://user-images.githubusercontent.com/17067417/28635292-0bd63fa8-7208-11e7-9fa1-8a972ab60fa6.png">

In this case

http://kb.example.com/jsonapi/api/files

should be

https://kb.example.com/api/files

1.  This particular server is HTTPS, but the sample path us HTTP
2.  'jsonapi' is being added to the path.

I'm assuming this is a problem in `OpenApiDocs::generateDocsFromQuery()`, but didn't see exactly what was wrong.

**Comment by e0ipso** [comment]
Good catch! Please open a bug report against the Open API module.

**Comment by mdonadio** [comment]
Upstream issue, https://www.drupal.org/node/2897665
