### ISSUE TITLE
Create backend example for https://github.com/gothinkster/realworld

### ISSUE THREAD

**Issue by larowlan** [contentacms/contenta_jsonapi#162]
Worth adding a Drupal backend example for https://github.com/gothinkster/realworld?

Spec is here https://github.com/gothinkster/realworld/tree/master/api

**Comment by dawehner** [comment]
Thank you for the idea. We had a similar discussion before, see https://github.com/contentacms/contenta_jsonapi/issues/95 but its tricky, given that realworld defines how the API has to work, which, well, is tricky in Drupal.

**Comment by larowlan** [comment]
thanks, sorry I didn't search first
