### ISSUE TITLE
Unable to install via composer: Fatal error: Allowed memory size of 1073741824 bytes exhausted

### ISSUE THREAD

**Issue by mherchel** [contentacms/contenta_jsonapi#163]
I have my command line PHP set to 1024M, and I'm getting errors. I can continue upping it, but IMHO 1024 is already abnormally high. Is there anything I can do differently?

```
➜  contenta composer create-project contentacms/contenta-jsonapi-project MYPROJECT --stability dev --no-interaction
Installing contentacms/contenta-jsonapi-project (dev-8.x-1.x 4dc25ff1e8981e73ec8431e5b48fa9e0b13d9db7)
  - Installing contentacms/contenta-jsonapi-project (dev-8.x-1.x 8.x-1.x)
    Cloning 8.x-1.x from cache

Created project in MYPROJECT
Loading composer repositories with package information
Updating dependencies (including require-dev)

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 32 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Rule.php on line 60

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.%
➜  contenta php -r "echo ini_get('memory_limit').PHP_EOL;"
1024M
```

**Comment by cjgratacos** [comment]
@mherchel which PHP version are you using?

_Sent from my Lge LG-H918 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mherchel** [comment]
@cjgratacos Command line PHP is 5.5.26.

**Comment by cjgratacos** [comment]
@mherchel thanks, I have seen that happen before, it is caused by the composer infinite chain of dependency in one of the packages and a PHP 5.x memory issue. A way to resolve it is by changing the `memory_limit` field to `-1` in the `php.ini` while composer is installs, after it is done you can revert it back to the old value.

**Comment by mherchel** [comment]
FWIW I did a `composer self-update` as well as change my command line PHP to 7.0.something, and I was able to get it installed.

**Comment by katiakweb** [comment]
The only thing that fix my problem with composer out of memory was this:

/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1

REF:https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors

I hoje this can help someone...

**Comment by lilikzone** [comment]
https://github.com/katiakweb

Great job, yo get the solutions..... teriamakasih

**Comment by steveorg** [comment]
If your running Cpanel with PHP-FPM, you may need to make sure your "inherit" value memory is set to the error specified limit as well. When I ran a check of the values in composer, it listed my correct non-inherit PHP version's memory limit, however, it ended up using the system's inherit value when running commands. 

This is probably a Cpanel PHP versioning issue, but hopefully it will help someone out.

**Comment by tamzidoronno** [comment]
> The only thing that fix my problem with composer out of memory was this:
> 
> /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
> /sbin/mkswap /var/swap.1
> /sbin/swapon /var/swap.1
> 
> REF:https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors
> 
> I hoje this can help someone...

This is the real solution! thanks!
