### ISSUE TITLE
Add a dev dependency on features

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#17]
We want to move `recipes_magazin` into the profile so we can diverge the data model from ootbei.

We also want a dev dependency on features:

![slack - drupal 2017-05-24 10-15-59](https://cloud.githubusercontent.com/assets/1140906/26393420/0ee571c0-406a-11e7-889a-2a33ced270cc.png)

**Comment by dawehner** [comment]
We have fixed both bits, right? I think we can close this ticket now.
