### ISSUE TITLE
Change Contenta theme colors 

### ISSUE THREAD

**Issue by yann-yinn** [contentacms/contenta_jsonapi#175]
Hello !
Default colors from the theme are pretty dark and a little bit sad. A graphist friend of mine ( @FlorisMoriceau ), suggested this design change for the colors : he uses the logo color for the header and a lighter background,  I find this color palette more engaging, what do you think about it ?

Actual : 
<img width="750" alt="contenta-colors" src="https://user-images.githubusercontent.com/335495/29739340-dbef236c-8a3b-11e7-9220-9c5b17d5e915.png">

Proposal : 
![contenta-new-colors](https://user-images.githubusercontent.com/335495/29739343-e86562b4-8a3b-11e7-9a65-46c689a33163.png)

**Comment by e0ipso** [comment]
Paging @ckrina for an opinion on this.

**Comment by ckrina** [comment]
Thanks @e0ipso :)
I totally agree with @nyl-auster and @FlorisMoriceau about the the "sad" perception of the interface: I think everything is a bit dark, and also the greys are too green. On this screenshot the page looks much more cleaner.
But I'm not sure if I'd use the bright blue on the header. This color was picked to be the primary button color in forms so it could stand out among the other elements. I agree that it's much more  appealing, but seeing it all the time can be tiring. Maybe just using it in some places could help on that?

**Comment by e0ipso** [comment]
FYI this is the **current** look of Contenta: http://cms.contentacms.io and http://cms-dev.contentacms.io

**Comment by yann-yinn** [comment]
@e0ipso it's nice ! this is not the one i saw when installing contenta following this process ,do you know why ? https://yineo.fr/blog/en-how-to-install-contenta-cms-on-pantheon-with-terminus

**Comment by e0ipso** [comment]
@nyl-auster I believe that Pantheon is fixed to an old commit.

Maybe @greg-1-anderson can clarify.

**Comment by yann-yinn** [comment]
@e0ipso you're right, from a fresh install i got this , so i am closing this issue
<img width="1396" alt="capture d ecran 2017-08-27 a 13 59 06" src="https://user-images.githubusercontent.com/335495/29749548-146a90f2-8b2f-11e7-95c7-c5a8b04071ba.png">

**Comment by greg-1-anderson** [comment]
I couldn't read the blog above - got a server error when I clicked on the link.

The Pantheon experimental Contenta installation project is pinned to [dev-8.x-1.x](https://github.com/pantheon-systems/example-drops-8-composer/blob/contenta/composer.json#L20). I'd be happy to change that to something else if there's a more appropriate version constraint now.

**Comment by yann-yinn** [comment]
@greg-1-anderson yes i unpublished my blog post because i would not recommend this version of contenta ( as i opened 3 issues for things that have been resolved in current contenta version)

**Comment by greg-1-anderson** [comment]
What is the "current contenta version", though? It looks to me as is 8.x-1.x is still the appropriate branch for dev releases?  Maybe you installed the dev version a while ago? If so, you might simply need to update your site. Use `composer update` on a local working copy of your site's GitHub repository.

It would be helpful if there were SemVer release tags for the contenta distribution.

**Comment by yann-yinn** [comment]
@greg-1-anderson

I dont know about the versions ( cc @e0ipso ), just for information : 

this is the command I ran this week-end with terminus 
```
terminus build:project:create pantheon-systems/example-drops-8-composer:dev-contenta YOUR-SITE-NAME
```

And then i ran this command in my localhost to reinstall it from scratch
```
composer create-project contentacms/contenta-jsonapi-project MYPROJECT --stability dev --no-interaction
```

**Comment by greg-1-anderson** [comment]
Not sure if this is what you were trying to say, but that second command is not an appropriate way to update a Pantheon Contenta site. You could use that `composer create-project` to create a non-Pantheon Contenta site for local use. To update a site created with `terminus build:project:create`, use `composer update`.

**Comment by yann-yinn** [comment]
@greg-1-anderson 

I used the _first command_ to create automatically a pantheon site. And that works very well but it gave me the first screenshot from this issue, and i was missing some modules ( snail ). **I dit not try** to update the pantheon site at this point, because, well, it was freshly installed. I told myself that maybe terminus must have built something from an outdated contenta release tag.

From then, i deleted my pantheon site and I used the _second command_ on my local and saw that it gave me a version of contenta with the right theme and modules I needed.

Shit this issue is a mess, i am so sorry people, just wanted to give a bit of light to the dark theme  xD

**Comment by greg-1-anderson** [comment]
I would think those two commands should give you about the same Contenta, given that you ran them at the same time. Maybe add `--stability dev` to the Terminus command, as you have in the `composer create-project` command? That could explain some differences in project versions.

**Comment by e0ipso** [comment]
@greg-1-anderson can this be related to `composer.lock` using an old version?

https://github.com/pantheon-systems/example-drops-8-composer/commit/c6ab421dd1757dc8386aef66907bfe79e42bfbbf#diff-1da2c7edc898c70e5a79a9997c98ceccR392

**Comment by greg-1-anderson** [comment]
Yeah, makes sense. `composer update` will fix that.

**Comment by e0ipso** [comment]
@nyl-auster can you try that and see if it works? Maybe you can re-post the article after that.

**Comment by yann-yinn** [comment]
@e0ipso sorry i already deleted this site. But i guess i can just add "composer update" to my blog post ?

**Comment by greg-1-anderson** [comment]
I'll remove the composer.lock file from the PR

**Comment by greg-1-anderson** [comment]
Done; tests are running at https://github.com/pantheon-systems/example-drops-8-composer/pull/93
