### ISSUE TITLE
Remove "display settings" and "menu settings" when creating a content model ?

### ISSUE THREAD

**Issue by yann-yinn** [contentacms/contenta_jsonapi#177]
Some configuration for content types became irrelevant when using contenta, maybe just add a warning or something ?

<img width="1336" alt="capture d ecran 2017-08-27 a 14 17 26" src="https://user-images.githubusercontent.com/335495/29749672-b9932b46-8b31-11e7-9356-cad3699c65c3.png">

**Comment by dawehner** [comment]
Good idea!

What would be a good place to strip away configurations you don't need on a decouple site? Maybe a new module like a ```decouplifier```?

**Comment by e0ipso** [comment]
I think that'd be awesome. It's going to be a big challenge in a CMS so flexible because both blacklisting and whitelisting will require constant maintenance (think about a module you didn't know about).

Any ideas how to deal with that?

**Comment by yann-yinn** [comment]
and should we remove it totally ? not sure about that, what if, for whatever reason, you want to use one part of Drupal 'as it is for' some part of your site ? 

@e0ipso we can just care about the core, maybe that's better than nothing. Just to make it clear that those settings have no effects on JSON output.

**Comment by dawehner** [comment]
Aren't the menu settings actually for example potentially useful? I could
imagine that people maybe would see an advantage in controlling the menu as
an editor? Of course this should be an opt in feature for some frontends
but I could see it to be useful.



Yann <notifications@github.com> schrieb am Mi., 30. Aug. 2017 um 11:35 Uhr:

**Comment by yann-yinn** [comment]
@dawehner yep you're right, menu can be used from the consumer ...

**Comment by e0ipso** [comment]
👋🏽 @nyl-auster, it's been a while. I hope all is good!

I think we agreed that we want to leave this as is. Thanks all. I'm going to close this.
