### ISSUE TITLE
Gather content for the Knowledge Hub (/help/tutorials) page

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#187]
We want to have an initial list of links with the following information:

  - [ ] Title (required).
  - [ ] Description (required).
  - [ ] Link (required).
  - [ ] Image (optional).

**Comment by e0ipso** [comment]
Example:

Title | Description | Link | Image URL
-----|------------|------|-----------
The Hidden Costs of Decoupling | Decoupled Drupal has been well understood at a technical level for many years now. While the implementation details vary, most Drupal teams can handle working on decoupled projects. However, we’ve heard the following from many of our clients | https://www.lullabot.com/articles/the-hidden-costs-of-decoupling | https://assets.lullabot.com/styles/dynamic_resize/w960/ben-cliff-230075.jpg
Should you Decouple? | One of the major topics of discussion in the Drupal community has been decoupled (or headless) Drupal. Depending on who you ask, it’s either the best way to build break-through user experiences, or nothing short of a pandemic. But what exactly is a decoupled architecture? | https://www.lullabot.com/articles/should-you-decouple | https://assets.lullabot.com/styles/dynamic_resize/w960/ben-cliff-230075.jpg
The 3 C's + the 1 D of Drupal: Why Decoupled Matters | Decoupled has been in place for a few years, but the Open Source and Drupal community are really beginning to rally around it, as evidenced by more than 100 professionals gathering in NYC last weekend at 30 Rock.| https://www.mediacurrent.com/blog/3-cs-1-d-drupal-why-decoupled-matters | https://www.mediacurrent.com/sites/default/files//decoupled-three_cs.png

**Comment by eojthebrave** [comment]
What kind of information/tutorials are you hoping to include in the knowledge hub?

**Comment by e0ipso** [comment]
I think that any resource that can help clarify concepts about decoupled Drupal projects for agencies or freelancers.

I think that either technical, project manager (specific to decoupled Drupal projects), sales and estimation, etc. all make sense.

**Comment by kepford** [comment]
Here are some decoupled related blog posts worth considering

| Title | Description	| Link                                                                                   | Image URL  |
|-----------------------------------------------------------------------|-------------|----------------------------------------------------------------------------------------|------------|
| 4 Benefits of decoupled architecture for enterprise digital marketers | A non-developer focused article on decoupled architecture from Mediacurrent's Shellie Hutchens. | http://www.mediacurrent.com/blog/4-benefits-decoupled-architecture-enterprise-digital-marketers                                     |
| Decoupled Drupal and Ember                                            | "This is the first in a series of articles that will document lessons learned while exploring using Ember as a decoupled client with Drupal."| http://www.nextide.ca/decoupled-drupal-with-ember-part1
| Decoupled static music site using Drupal + Pushtape Cassette          | Looks like a fun way to play with decoupled Drupal and music. | http://zirafaworks.com/note/decoupled-static-music-site-using-drupal-pushtape-cassette
| React and Drupal 8 with JSON API 2/3                                  | If you're looking at experimenting with decoupled Drupal be sure and read this post. JSON API is a great way to expose you content to a decoupled frontend app.| https://colorfield.be/blog/react-and-drupal-8-json-api-2
| Decoupled Drupal with Ember: Introducing Ember and JSON API           | "In this two-part series intended to help you attain escape velocity quickly, we’ll explore the inner workings of Ember, foundational concepts of Ember's ecosystem, how to decouple Drupal with an Ember front end, and what the future could bring in terms of more Ember within Drupal. By the end, we’ll have assembled a simple Drupal content browser powered by Ember." | https://dev.acquia.com/blog/decoupled-drupal-with-ember-introducing-ember-and-json-api/14/12/2016/17366
| Progressively Decoupled Drupal Approaches                             | "This blog post features some compelling approaches which reflect a wide spectrum of possible ways to implement Drupal in a progressively decoupled fashion without abandoning the things that make Drupal great on the front end. " | https://dev.acquia.com/blog/progressively-decoupled-drupal-approaches/22/08/2016/16296
| Between the Cracks of Decoupled (Drupal) Architecture                 | In this article Campbell Vertesi provides a very insightful look at the issues that can arise when you add the complexity of a decoupled architecture.| https://ohthehugemanatee.org/blog/2017/02/11/a-year-between-the-cracks-of-decoupled-drupal/
| Drupal and Graphql with React and Apollo                              | This blog post shows how you can easily use Drupal 8, React, GraphQL, and Apollo to build an app that displays a list of articles. | https://www.amazeelabs.com/en/blog/drupal-graphql-react-apollo
| Decoupling in drupal 8 based on a proven model                        | Matt Davis of Mediacurrent introduces us to a module that provides the ability to progressively decouple blocks in Drupal 8. | https://www.mediacurrent.com/blog/introducing-decoupled-blocks-module-decoupling-drupal-8-based-proven-model
| Re-learning accessibility for a decoupled front end                   | Tobias Williams reminds us that when decoupling Drupal, we need to thinking more about accessibility. A good refresher. | https://www.mediacurrent.com/blog/re-learning-accessibility-decoupled-front-end
| Using Drupal 8 contact forms via REST                                 | A solution to a commonly requested feature in decoupled sites. | https://www.svendecabooter.be/blog/using-drupal-8-contact-forms-via-rest

**Comment by e0ipso** [comment]
Thanks @kepford! I added the articles. I omitted one about Ember to avoid repetition, but everything else went it.

**Comment by e0ipso** [comment]
I think this was of great help.
