### ISSUE TITLE
Debug: Key file "file://" permissions are not correct, should be 600 or 660 instead of 555 in League\OAuth2\Server\CryptKey->__construct() (line 56 vendor/league/oauth2-server/src/CryptKey.php)

### ISSUE THREAD

**Issue by MatthieuScarset** [contentacms/contenta_jsonapi#190]
Hi, I have a warning right after a fresh install of Contenta.

```
Debug: Key file "file://" permissions are not correct, should be 600 or 660 instead of 555 in League\OAuth2\Server\CryptKey->__construct() (line 56 of vendor/league/oauth2-server/src/CryptKey.php).
``` 

My `composer show` shows that I am using the latest version: `league/oauth2-server 6.0.2`

**Comment by sebas5384** [comment]
We are having same issue over here, and is giving that error in Acquia Cloud too.

**Comment by e0ipso** [comment]
Please check the configuration steps in http://cms.contentacms.io/help/tutorials?field_topic_value=OAuth2

If that doesn't fix your issue, comment back and I'll reopen the ticket.

**Comment by MatthieuScarset** [comment]
For the lazy ones who want to know what need to be done, you can see here too:
https://github.com/MatthieuScarset/matt-back-drupal/blob/dev/certificates/README.md
