### ISSUE TITLE
Oauth2Client' not found

### ISSUE THREAD

**Issue by spoetnik** [contentacms/contenta_jsonapi#196]
Installed Contenta with:
`composer create-project contentacms/contenta-jsonapi-project contenta --stability dev --no-interaction`
After installation, navigating to API -> Authentication (/admin/api/authentication)
results in an error:
```
The website encountered an unexpected error. Please try again later.
Error: Class 'Drupal\simple_oauth\Entity\Oauth2Client' not found in Drupal\contenta_enhancements\Controller\ApiAuthInfo->info() (line 21 of profiles/contrib/contenta_jsonapi/modules/contenta_enhancements/src/Controller/ApiAuthInfo.php).
```

**Comment by e0ipso** [comment]
Thanks @spoetnik! This is fixed now.
