### ISSUE TITLE
Exception raised on front if media_entity module is disabled

### ISSUE THREAD

**Issue by MatthieuScarset** [contentacms/contenta_jsonapi#197]
Issue:
It is not possible to use `contenta_enhancements` module if you do not enable `media_entity` because a link is added in the toolbar but it uses a non-existing route (`view.media.media_page_list`).

Instead of adding `media_entity` as a dependency, it would be better to allow users to disable the `media_entity` module and still `use content_enhancements`.

Proposed solution:
Test if `media_entity` module is enabled before adding the link.

**Comment by MatthieuScarset** [comment]
PR here: https://github.com/contentacms/contenta_jsonapi/pull/198

**Comment by e0ipso** [comment]
PR was merged.

Thanks!
