### ISSUE TITLE
Stack Cors patches don't apply anymore

### ISSUE THREAD

**Issue by recidive** [contentacms/contenta_jsonapi#199]
As of today, I'm seeing this error when installing contenta via composer:

```
  - Applying patches for asm89/stack-cors
    https://patch-diff.githubusercontent.com/raw/asm89/stack-cors/pull/42.patch (Add origin matcher for wildcard matching)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://patch-diff.githubusercontent.com/raw/asm89/stack-cors/pull/42.patch
    https://github.com/asm89/stack-cors/commit/6daf5757971173b79ddabbd755d59d333c278f42.patch (Do not modify request with same origin)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://github.com/asm89/stack-cors/commit/6daf5757971173b79ddabbd755d59d333c278f42.patch
```

**Comment by MatthieuScarset** [comment]
I do too

**Comment by dawehner** [comment]
> As of today, I'm seeing this error when installing contenta via composer:

Oh is this because you are running a more up to date version of the upstream library?

**Comment by sebas5384** [comment]
@dawehner are you saying as a dependency of Contenta? if it is, then should we lock the version at the composer.json (of Contenta) till those patches are updated?

**Comment by recidive** [comment]
@dawehner yes, since drupal core doesn't add composer.lock to the repository and doesn't lock that library on a specific version, any time you install contenta it will install the latest version of the library along with drupal core, and the patches are not applying in the latest version.

**Comment by recidive** [comment]
Here is the install log with details on the library version:

```
Gathering patches for dependencies. This might take a minute.
  - Installing asm89/stack-cors (1.1.0)
    Loading from cache

  - Applying patches for asm89/stack-cors
    https://patch-diff.githubusercontent.com/raw/asm89/stack-cors/pull/42.patch (Add origin matcher for wildcard matching)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://patch-diff.githubusercontent.com/raw/asm89/stack-cors/pull/42.patch
    https://github.com/asm89/stack-cors/commit/6daf5757971173b79ddabbd755d59d333c278f42.patch (Do not modify request with same origin)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://github.com/asm89/stack-cors/commit/6daf5757971173b79ddabbd755d59d333c278f42.patch
```

**Comment by e0ipso** [comment]
What's the solution here? I see 2 possible options:

👍  Have a more restrictive locking of the library in Contenta's `compose.json`
❤️  Have a loose version and let the patch fail when needed.

Votes?

**Comment by dawehner** [comment]
I think the best approach would be to update stack-cors to the latest version, lock it, and then provide patches which apply again, if needed inside the distribution itself.

**Comment by e0ipso** [comment]
We don't have that patch anymore.
