### ISSUE TITLE
Show the about US page after installation

### ISSUE THREAD

**Issue by dawehner** [contentacms/contenta_jsonapi#20]
I think it would be useful to show the about US page right after the installation.

**Comment by e0ipso** [comment]
I fully agree that we need a nicer front page after install. _About us_ is the only decent choice we have at the moment. I vote to use _About us_ for now and create a better landing page later.

I will create a follow up ticket to add a landing page.

**Comment by dawehner** [comment]
Let's use the "help wanted" tag, if possible?
