### ISSUE TITLE
Media Entity module in 8.4 is part of the core

### ISSUE THREAD

**Issue by sebas5384** [contentacms/contenta_jsonapi#201]
See https://www.drupal.org/project/media_entity on the **Compatibility restrictions** part.

We are having some errors given the media and media_entity are enabled:

```
[error]  Configuration objects provided by <em class="placeholder">media</em> have unmet dependencies: <em class="placeholder">core.entity_form_display.media.image.default (image.style.thumbnail), core.entity_view_display.media.image.default (image.style.medium)</em>
```

```
[error] 290#290: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare template_preprocess_media() (previously declared in /drupal/app/web/core/modules/media/media.module:89) in /drupal/app/web/modules/contrib/media_entity/media_entity.theme.inc on line 46
```

How should we deal with this situation, since older versions of Drupal 8 are going to need the media_entity module.

For now we are just disabling:
- media_entity
- media_entity_image
- media_entity_browser

**Comment by woprrr** [comment]
We need to Check all listed errors but you have enabled media and media_entity in same Time ?

**Comment by dawehner** [comment]
As far as I understand Drupal 8.4. does not recommend yet to use media, as the contrib space is not updated fully yet.

**Comment by e0ipso** [comment]
I agree with Daniel here as well. We need to wait a bit more for the media ecosystem.

Feel free to request a re-open.

**Comment by woprrr** [comment]
@dawehner @e0ipso Actually for basics usage like manipulate Image/video I think we can use that in contentacms like lightning ? @see https://www.drupal.org/node/2860796 to follow all media provider states.

If you need I can purpose to test and take feedback about usability and fesability of media in core usage ?

**Comment by e0ipso** [comment]
That's a great offer @woprrr! Thank you in advance.
