### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by novia713** [contentacms/contenta_jsonapi#202]
¿is available some method to document the API in Contenta?
¿would be possible install something like http://apidocjs.com?

**Comment by dawehner** [comment]
@novia713 At least for me the most important APIs are the HTTP apis we expose. 
I'm curious, what is your usecase to need to know more of the HTTP apis?

Also, how hard is it to setup something like apidocjs.com? I guess we could just put it on now.sh or so and call it a day?

**Comment by novia713** [comment]
well, all i need is to document the API i'm building, @dawehner 
regarding my first question, i only wished to know is there was in Contenta some type of integration with PHP API Documentors (like Swagger-PHP). only that.
I know how to set up swagger or apidocjs, but thanks for the hint  ^^

**Comment by e0ipso** [comment]
@novia713 I think this is what you're looking for: http://cms.contentacms.io/admin/api

It comes with Contenta CMS by default. I believe it's communicated in different places. Did you find the documentation hard to find?

**Comment by novia713** [comment]
oh, yes, @e0ipso 
i opened the issue before checking that API section in admin part.
i believe this is enough.
my apologies.

**Comment by e0ipso** [comment]
No need to apologize. Just making sure we don't have a UX problem to help discover that feature

**Comment by novia713** [comment]
no, just i've opened my big mouth before checking well the site :-)
