### ISSUE TITLE
[IDEA] Education resources as demo content

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#21]
Here is an idea.

What if we added some tutorial content as demo content. That way when you install Contenta CMS you get a list of _Tutorials_ on different topics:

  * How to make queries against the provided content model.
  * How to create content (recipe reviews) using the API.
  * How to authenticate your requests.
  * How to set CORS to match your domain.
  * How to deal with routing.
  * …

We could provide this content as web pages in Contenta (rendered with the admin theme, it's fine for now) along with the demo content. When you're done you uninstall the demo content and the tutorials are gone and you're left with the site you configured thanks to the tutorials.

With this idea we meet 2 goals:
  1. Knowledge base right there.
  2. Enhanced demo content and richer content model.

**Comment by e0ipso** [comment]
These tutorials could be as simple as YouTube embeds with sample code, or even TL;DR of existing blog posts with a link to the original post, etc.

**Comment by e0ipso** [comment]
This would also be a great place for people to contribute with a low barrier of entry.

**Comment by dawehner** [comment]
Seems totally reasonable! We should somehow ensure that there is a limit of documentation and we refer to drupal.org for further details.

**Comment by e0ipso** [comment]
@dawehner absolutely. All the generic documentation should live in drupal.org. This would be for things that have a Contenta CMS dependency, for instance examples depending on the content model.

**Comment by e0ipso** [comment]
@dawehner should we create follow ups for this?

**Comment by stevector** [comment]
@e0ipso, @dawehner, can this issue be closed? [Tutorial content is present at install](https://github.com/contentacms/contenta_jsonapi/blob/8.x-1.x/modules/recipes_magazin_contenta/default_content/tutorial.csv).

**Comment by e0ipso** [comment]
@stevector you are correct. The issue queue could use a good triage.
