### ISSUE TITLE
How to install contenta_jsonapi with drush si without demo content

### ISSUE THREAD

**Issue by Ruslan03492** [contentacms/contenta_jsonapi#211]
How to install contenta_jsonapi with drush si without demo content?
I am try use `drush si contenta_jsonapi --include-recipes-magazin=0` but have error.

**Comment by Ruslan03492** [comment]
I found a solution `install_configure_form.include_recipes_magazin=0`

**Comment by e0ipso** [comment]
Thanks for closing the loop on this one @Ruslan03492.
