### ISSUE TITLE
Allow querying redirections

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#212]
A decoupled site may want to be able to support redirections of old URLs in a given content page.

A suggested solution is to provide a custom endpoint that takes a URL and returns either:

  - a 404.
  - the current canonical URL for that.

That should query both the URL aliases and the [redirect](https://www.drupal.org/project/redirect) module.

**Comment by dawehner** [comment]
Isn't that exactly what the redirect module is doing? It uses entities, so everything is queryable

**Comment by e0ipso** [comment]
My wish is to have that with URL aliases as well in the same resource.

**Comment by dawehner** [comment]
Why do you not make an entity reference then? The only missing bit is a
nice widget then

**Comment by e0ipso** [comment]
That sounds interesting. Although I don't think I got it.

A simplified version of what I think it's most useful is that a query to `https://cms.contentacms.io/api/redirects?filter[…]=/foo/bar` returns `{ … "/node/75" … }`. This endpoint will return exactly the same if `/foo/bar` is a redirect or a URL alias.

Is that what you're thinking too?
