### ISSUE TITLE
Composer install fails due to errors downloading dependencies.

### ISSUE THREAD

**Issue by shawnachieve** [contentacms/contenta_jsonapi#215]
When setting up a new contentacms via composer, the composer install fails with the following errors:

>    Failed to download contentacms/contenta-jsonapi-project from source: Failed to clone https://github.com/contentacms/contenta_jsonapi_project.git via https, ssh protocols, aborting.
>
> - https://github.com/contentacms/contenta_jsonapi_project.git
>  Cloning into 'contentacms'...
>  sh: line 0: cd: contentacms/: No such file or directory
>
> - git@github.com:contentacms/contenta_jsonapi_project.git
>  Cloning into 'contentacms'...
>  sh: line 0: cd: contentacms/: No such file or directory

> [RuntimeException]
>  Failed to execute git clone --no-checkout 'https://git.drupal.org/project/material_admin' 'web/themes/contrib/material_admin' --dissociate --reference
>  '/Users/shawn.smiley/.composer/cache/vcs/https---git.drupal.org-project-material-admin/' && > cd 'web/themes/contrib/material_admin' && git remote add composer 'https://git.drupal.org/project/material_admin' && git fetch composer
>  Cloning into 'web/themes/contrib/material_admin'...
>  sh: line 0: cd: web/themes/contrib/material_admin: No such file or directory

Steps to reproduce:
```
cd ~\Sites
composer create-project contentacms/contenta-jsonapi-project contentacms --stability dev --no-interaction
```

**Comment by cjgratacos** [comment]
@shawnachieve can you please give a bit of more context on the environment which you are using: OS, PHP Mods enabled, PHP Version, etc. Thanks in advance

**Comment by shawnachieve** [comment]
OS: Mac OS 10.12.6
PHP: 7.1.8
Composer: 1.4.2

My local PHP install is pretty minimal as I use vagrant VMs for the actual code execution.  I generally only run php/composer commands locally to install/update Drupal core and contrib modules.

**Comment by e0ipso** [comment]
I fear this has gone stale. Versions have changed quite a lot. Please request a re-open if necessary.
