### ISSUE TITLE
Create a nice toggle for JSON API vs GraphQL

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#216]
Once GraphQL has been added we want an easy way to turn on/off all the dependencies that make up a:

  - JSON API interface: jsonapi, jsonapi_extras, openapi, schemata, … (maybe contenta_jsonapi?)
  - GraphQL interface: …

I may be crazy to be thinking of the `features` module?

**Comment by dawehner** [comment]
@e0ipso You can totally uninstall modules when they ship their configuration. Given that we could have a contenta_jsonapi and a contenta_graphql module which ship with all their associated configuration. On top of that we would just need buttons for the modules.

Features doesn't do anything on runtime in D8. It is just a bundler.

**Comment by e0ipso** [comment]
Right. I was thinking that most of those modules don't ship any configuration. Will that be a problem?

**Comment by dawehner** [comment]
Maybe we could also "just" provide a UI which does the necessary uninstall calls, when we actually need them?

**Comment by e0ipso** [comment]
cc @cjgratacos since I know you may be onto this now.

**Comment by e0ipso** [comment]
This was done.
