### ISSUE TITLE
revision info getting collection

### ISSUE THREAD

**Issue by novia713** [contentacms/contenta_jsonapi#217]
i'm retrieving data of a collection, but i can't get any data of the field `revision_uid`
the query i'm using is: 
```
node/operation?filter[revision_uid.uuid][value]=7520b429-...
```
the error is 
```json
"errors": [
        {
            "title": "Internal Server Error",
            "status": 500,
            "detail": "'revision_uid' not found",
         }
]
```
am i missing something?

**Comment by e0ipso** [comment]
This is because this field is disabled by default. You can enable it if needed. Go to: `/admin/config/services/jsonapi/node--recipe/edit`.

![2018-04-27 08-03-45](https://user-images.githubusercontent.com/1140906/39347118-ac75f6b2-49f1-11e8-9910-630f04cab84e.png)
