### ISSUE TITLE
Create content for a front page

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#22]
After #20 lands we'll have a landing page after installation. It will be set to the _About us_ page. However we want to have a page that is more dedicated to explain _next steps_ after installation.

I'm thinking of the scenario _… ok, I have this installed. What now?_

We'll need:
  - [x] Content for the front page.
  - [ ] Design for the front page (it can come later as a follow up).

Dependencies:
  - [x] Page migration so the content for the page can be just a set of CSV rows in existing files.

**Comment by e0ipso** [comment]
Pinging @ckrina in case she has ideas about how this could look like.

**Comment by ckrina** [comment]
I completely agree on having a separate page for steps after install, different from the _about us_. Exactly what can be there I am not sure, but it will depend on what actions can actually be done. 
So ideally there should something like "you are here (and have done that so far)". An later some actions (with call to action for each):
- Read more info/links to documentation
- Create content from current content types
- Create new content types
- See content (...)
- Configure/change API settings?

Some questions:
- Is any remaining set up needed when they are here?
- Do we have any preference about what should be their steps?

**Comment by e0ipso** [comment]
This is my initial proposal.

Thoughts are much appreciated.

---

OK! I just installed Contenta CMS, now what?

First of all, congratulations! We know that trying new software can be both fun and also a little bit intimidating. In any case we are glad to see that you are giving this a shot.

From here there are two different paths you can follow next:

  * You can explore the capabilities of decoupled Drupal from the backend perspective.
  * You can revert the site to a clean state and remove all the demo content and configuration.

## Exploring Contenta CMS
The first two things you want to do are:

  1. Go to the [content types configuration page](/admin/structure/types) and explore the different content types and their fields to understand what you are going to be exposing.
  2. Head over to the content list page to see the demo content that you can interact with.

One of the first things that you may want to do is to understand what your API looks like. Read about [Understanding API Schemas](/understanding-api-schemas) to know more.

Once you understand what is the schema of your API and what it will look like, is't time for you to start [Making Your First Request](/making-your-first-request).

The section about [Creating Content Using the API](/creating-content-using-the-api) will give you information about how you can use the API to write content to Contenta, instead of just reading from it.

It is possible that you will need to make [Authenticated Requests](/authenticated-requests). That's fine too, we have you covered. Contenta comes with OAuth support out of the box.

Finally, if you are a perfectionist you will probably want to learn how to aggregate your requests for performance reasons. JSON API makes it really easy to have very few requests, however some times you just want [One Request to Rule Them All](/one-request-to-rule-them-all).

## Reverting to a Clean State
You have already explored what contenta can offer out of the box, now you are ready to start building your project.

In order to revert Contenta to a clean slate you will need to uninstall the _Recipes Magazin_ and the _Recipes Magazin Contenta_ modules. By uninstalling those modules you will:

  * Remove the demo content types: Recipe, Page and Article.
  * Remove the customizations to clean the API of Drupalisms.
  * Remove all the content for the demo content types. Even if you created the content after installing, if you remove the content types the content will be deleted.

Once those two modules are gone, you will have a clean Contenta CMS installation. Even this page and all the help content will be gone.

If you ever regret this decision, it's OK! By re-enabling those two modules you will get everything back.

**Comment by e0ipso** [comment]
@dawehner @ckrina is this the direction you had in mind?

**Comment by dawehner** [comment]
I'd have swapped the text about authentication and creating content. Once we have front-ends I'd link them from this document

**Comment by e0ipso** [comment]
I added the content to the migration.

**Comment by e0ipso** [comment]
This was done
