### ISSUE TITLE
Update to Drupal 8.4.x

### ISSUE THREAD

**Issue by dawehner** [contentacms/contenta_jsonapi#223]
We should update to Drupal 8.4.x, given that 8.3.x is not longer supported

* We will use media in contrib, till core and the ecosystem provides all the necessary tools (probably for 8.5.x)
* #199 You can probably get rid of some of the cors patches now
* We need to reexport some of the configuration probably.

**Comment by cjgratacos** [comment]
@dawehner I am going to start working on this one, going to ping you for questions 👍

**Comment by dawehner** [comment]
Totally

Carlos Gratacos <notifications@github.com> schrieb am Sa., 25. Nov. 2017 um
16:05 Uhr:
