### ISSUE TITLE
Install error with non-existent service "simple_oauth.key.generator"

### ISSUE THREAD

**Issue by PolywickStudio** [contentacms/contenta_jsonapi#228]
This is with command-line parameters:

>composer create-project contentacms/contenta-jsonapi-project PROJECT --stability dev --no-interaction

On Page4 I get:
![e1](https://user-images.githubusercontent.com/8903532/33412128-7a1ba9ba-d5c4-11e7-9397-3549215f25c5.PNG)

The website encountered an unexpected error. Please try again later.
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "simple_oauth.key.generator". in Drupal\Component\DependencyInjection\Container->get() (line 157 of core\lib\Drupal\Component\DependencyInjection\Container.php).
Drupal\Component\DependencyInjection\Container->get('simple_oauth.key.generator') (Line: 158)
Drupal::service('simple_oauth.key.generator') (Line: 39)
_contenta_jsonapi_generate_keys() (Line: 28)
contenta_jsonapi_install()
call_user_func_array('contenta_jsonapi_install', Array) (Line: 391)
Drupal\Core\Extension\ModuleHandler->invoke('contenta_jsonapi', 'install') (Line: 287)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1572)
install_install_profile(Array) (Line: 662)
install_run_task(Array, Array) (Line: 540)
install_run_tasks(Array) (Line: 117)
install_drupal(Object) (Line: 44)

**Comment by e0ipso** [comment]
Can you please try again after the new updates to the repository?

**Comment by ralkeon** [comment]
Same error here! I tried 1 min ago. :grin:

**Comment by e0ipso** [comment]
@PolywickStudio @ralkeon it seems that your composer is pulling an outdated version of simple_oauth.

Can you post the version of `drupal/simple_oauth` inside `composer.lock` here?

**Comment by e0ipso** [comment]
Also, maybe try `composer clear-cache` before re-installing.

**Comment by ralkeon** [comment]
I've tried again after I cleared composer cache, but still the same error.
Here's the chunk of the composer.lock with simple_oauth version:
https://bitbucket.org/snippets/ralkeon/LeeLa6

**Comment by cjgratacos** [comment]
@ralkeon can you please share your `composer.lock` or a `composer show`,  and your OS versions and environment. Thanks in advance

**Comment by ralkeon** [comment]
Sure! 
I added composer.lock file here:
https://bitbucket.org/snippets/ralkeon/LeeLa6
my OS is Ubuntu 16.04
I have a machine with:
PHP 7.1
Apache 2.4.18
MySql 14.14 Distrib 5.5.41
Composer 1.5.5

Ask if need other info! Thank you so much!

**Comment by PolywickStudio** [comment]
I've moved on and using something else. 
I'll close the ticket. For the other people, please create a new ticket.

**Comment by e0ipso** [comment]
Something that's funny is that the screenshot shows `8.3.7` as the Drupal version. That should say `8.4.2` in the updated version. That tells me that there is something messing with your composer dependencies.

**Comment by e0ipso** [comment]
> I've moved on and using something else.

@PolywickStudio what will you be using instead?

**Comment by PolywickStudio** [comment]
https://github.com/api-platform/api-platform

**Comment by PolywickStudio** [comment]
> Something that's funny is that the screenshot shows 8.3.7 as the Drupal version. 

Don't ask me - ask the composer and the install instructions they provided.

**Comment by Al-Rozhkov** [comment]
I have same error. `You have requested a non-existent service "simple_oauth.key.generator". in Drupal\Component\DependencyInjection\Container->get()`

In composer.lock I have `"drupal/simple_oauth": "^3.3",`

**Comment by e0ipso** [comment]
@Al-Rozhkov is it also listing `8.3.7` as well for you?

**Comment by e0ipso** [comment]
@Al-Rozhkov can you provide the data @cjgratacos requested in https://github.com/contentacms/contenta_jsonapi/issues/228#issuecomment-348507143?

**Comment by Al-Rozhkov** [comment]
Nope. My Drupal version is 8.4.2
Here is my composer.lock: https://yadi.sk/d/3NN5I6HE3QFaEj

Windows 7
Apache 2.4.26
PHP 7.1.7
MySQL 5.5.5-10.1.25-MariaDB
Composer 1.5.2

**Comment by e0ipso** [comment]
@Al-Rozhkov @ralkeon @PolywickStudio can you share the command you used to install Contenta?

**Comment by Al-Rozhkov** [comment]
Sure. I followed instructions from http://www.contentacms.org/

`composer create-project contentacms/contenta-jsonapi-project MYPROJECT --stability dev --no-interaction`

**Comment by e0ipso** [comment]
@Al-Rozhkov thanks. That looks good. Can you try to repeat the install and paste here the output of it?

Make sure to do `composer clear-cache` before re-trying.

**Comment by Al-Rozhkov** [comment]
It works for me now.

Thank you @e0ipso! You doing great job! It is very interesting project.

**Comment by e0ipso** [comment]
@Al-Rozhkov thanks for the kind words! I hope it's useful to you.

I suspect that Composer was tripping on some cached dependency...

I'll close the issue for now. If anyone gets this again, please request a reopen.

**Comment by cjgratacos** [comment]
@e0ipso that is some awesome news. I tried to replicated in 4 different environment and for me it worked, everything was ok.

**Comment by ralkeon** [comment]
Hi all, sry for the delay.
I tryed again and I get the same error.
Then I've done another attempt, but this time I run the `composer create-project contentacms/contenta-jsonapi-project MYPROJECT --stability dev --no-interaction` command and after that I set chmod 777 and chown `myuser:www-data` on MYPROJECT folder. Finally I installed drupal, and it worked!!!
