### ISSUE TITLE
Can't update with composer

### ISSUE THREAD

**Issue by novia713** [contentacms/contenta_jsonapi#229]
is this normal? what should i do?

 ```
root@nsXXXXX1.ip-x-x-x-x.eu   master ↑1 U:1  ~/html/api_nexum  composer up --with-dependencies -o --prefer-dist

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
No patches supplied.
Gathering patches for dependencies. This might take a minute.
  - Updating contentacms/contenta_jsonapi dev-8.x-1.x (1c794e4 => 1589c19):     Update failed (Source directory web/profiles/contrib/contenta_jsonapi has unpushed changes on the current branch: 
A       config/sync/.htaccess
A       config/sync/coffee.configuration.yml
A       config/sync/core.base_field_override.node.client.promote.yml
A       config/sync/core.base_field_override.node.collaborator.promote.yml
A       config/sync/core.base_field_override.node.collaborator.title.yml
A       config/sync/core.base_field_override.node.date_assignement.promote.yml
A       config/sync/core.base_field_override.node.document.promote.yml
A       config/sync/core.base_field_override.node.document.title.yml
A       config/sync/core.base_field_override.node.employee.promote.yml
A       config/sync/core.base_field_override.node.employee.title.yml
... etc ...
```

**Comment by simesy** [comment]
Add
```
"discard-changes": true
```
into the config section of your composer.json, then run `composer update` again

**Comment by e0ipso** [comment]
Alternatively you can also run `COMPOSER_DISCARD_CHANGES=1 composer update …` as a one-time-thing.

However it seems that you're storing extra config inside of the distribution folder, and that seems wrong. You should have your site-owned cofig location.

**Comment by simesy** [comment]
Agreed ^^

**Comment by novia713** [comment]
@e0ipso @simesy i wonder how am i storing any confing, given i never did nor
`drush cex` nor `drupal ce`. also didn't never export config from the proper site ... :-(

**Comment by novia713** [comment]
also nor including in composer config `"discard-changes": true` nor giving the following command
`COMPOSER_DISCARD_CHANGES=1  composer up --with-dependencies -o --prefer-dist` the system founds any solution. so, the problem reamins.

i don't want to forget to say thanks for the project in general and specially for this problem in particular :-)

**Comment by e0ipso** [comment]
Can you clarify what the current error is? Did you ever get past it @novia713?

**Comment by e0ipso** [comment]
I'm leaning towards that this is a composer issue. Something is special about your setup / local environment.

Please request a re-open if you cannot get past this error.

**Comment by novia713** [comment]
this was months ago, i don't remind what i did, anyway it didn't show up anymore

**Comment by e0ipso** [comment]
Yay!
