### ISSUE TITLE
Feature request: Lando recipe

### ISSUE THREAD

**Issue by brookemahoney** [contentacms/contenta_jsonapi#233]
Any thoughts on doing a Lando recipe?

**Comment by e0ipso** [comment]
I think that would be a great idea! Probably related: https://github.com/contentacms/contenta_docker

**Comment by dawehner** [comment]
Sounds like a great task for someone to contribute!

**Comment by ziomizar** [comment]
I'm working on https://github.com/ziomizar/contentacms-lando is a fork of the nice work done by finnef for the phpunit initiative modified to run contenta with the full test suite out of the box.

**Comment by serundeputy** [comment]
I didn't make a Lando recipe, but I've got a set up that works well for our headless build:

* Set up: https://thinktandem.io/blog/2019/01/25/lando-contenta-cms-nuxt-pt-1/
* A first request: https://thinktandem.io/blog/2019/02/01/lando-contenta-cms-nuxt-pt-2/

I personally like the separation of the two different apps as it mirrors production API (Contenta CMS) as one app and a separate production Nuxt app.

It would not be too hard to put those in one `.lando.yml` file if one desired.
