### ISSUE TITLE
Support jwt

### ISSUE THREAD

**Issue by leonardosul** [contentacms/contenta_jsonapi#234]
Do you think there is any value in supporting [jwt authentication](https://www.drupal.org/project/jwt) ?

I'm thinking it might be useful for a SPA where all registration and authentication happens via an API request.

I think OAuth may be overkill for a site that just needs the usual Drupal user account stuff, but wants to decouple the front end. Storing the client ID and secret key on the front end obviously is not ideal, and having to add an intermediary service to store them may be prohibitive.

**Comment by e0ipso** [comment]
Simple OAuth has support for JWT already, and it's installed with Contenta. OAuth in that setup is just the (secure) flow you use to obtain a valid JWT from the server. For your SPA you'll want the _Implicit_ grant.
