### ISSUE TITLE
Creating New Consumers Fails

### ISSUE THREAD

**Issue by justinlevi** [contentacms/contenta_jsonapi#237]
Just playing around with the Contenta project and noticing that I can't create new consumers out of the box. Haven't dug in on this too much, but wanted to report the issue. 

![screenflow](https://user-images.githubusercontent.com/1117989/33808384-65443e70-ddb3-11e7-803d-39d75c556b3c.gif)

**Comment by e0ipso** [comment]
You need to create a new role and assign it to your consumer. That's what the error message is stating.

**Comment by justinlevi** [comment]
@e0ipso Thanks for the speedy response! 

I'm confused though as there are already the following roles and I'm unable to choose any of them on the "Add Consumer" screen. I'm likely missing something obvious...

![screen shot 2017-12-11 at 7 57 40 am](https://user-images.githubusercontent.com/1117989/33832226-50b3f5b8-de49-11e7-8576-71bfb5824cc4.jpg)

**Comment by justinlevi** [comment]
In other words, I can't create a consumer at all because of that error it seems.

**Comment by justinlevi** [comment]
:) Just as you said, I needed to create a new role first. Screen recording below. My vote would be to default to some reasonable initial roles that would be available on the create consumer screen. I think having reasonable defaults can reduce friction for beginners. 

Cheers and thanks again for all your hard work on this project!

![roles](https://user-images.githubusercontent.com/1117989/33832751-48939738-de4b-11e7-811f-30e62f9837fe.gif)

**Comment by e0ipso** [comment]
@justinlevi since the recommendation is to create a role per consumer, there is no way to create "sensible defaults".

What we could do is have some sort of UI to create a role with the name of the consumer when creating the consumer for the first time. Can you create an issue for that?

**Comment by justinlevi** [comment]
@e0ipso Where does the recommendation to create a role per consumer come from? Just trying to understand the background on this decision a bit more. I could definitely see the use case of wanting to use an existing role for several different consumers, but I'm likely missing something. 

I think defaulting to automatically creating a role for the new consumer would definitely help.

**Comment by e0ipso** [comment]
> Where does the recommendation to create a role per consumer come from?

The creators of _Consumers_, _Simple OAuth_ and _Contenta CMS_.

> I could definitely see the use case of wanting to use an existing role for several different consumers, but I'm likely missing something.

That is definitely a use case. Remember it's not enforced behaviors, just a recommendation.

**Comment by justinlevi** [comment]
Totally makes sense. Cheers.
