### ISSUE TITLE
Reduce new consumer creation friction - automatic role creation based on consumer name

### ISSUE THREAD

**Issue by justinlevi** [contentacms/contenta_jsonapi#238]
Based on the conversation here: https://github.com/contentacms/contenta_jsonapi/issues/237

It might reduce some friction to automatically create a role based on the consumer name. The current UX does not make it very clear that the role is required prior to creating the new consumer. Perhaps updating the help text, or providing some default message if no roles are available, would help as well. 

If there is no role available to select, having a default message like: 

"You must first create a role for this consumer to use." I would link the "Create a role" text as well.

**Comment by e0ipso** [comment]
Thanks for creating the issue @justinlevi.

This is the info we currently have. It may be that it's hard to find / understand. I agree that we should find a better UX.

![2017-12-11 15-44-18](https://user-images.githubusercontent.com/1140906/33836647-37bfd068-de8a-11e7-9eb1-9d2d51daf621.png)

**Comment by justinlevi** [comment]
Yeah, in retrospect I totally understand the help text and the role requirement. My first instinct is that the requirement of creating a role first needs to be indicated more clearly. It might just be me, but I found the help text and the error that is displayed when trying to create a consumer the first time, a bit confusing. 

I am still not sure why the default existing roles are not listed here though?
