### ISSUE TITLE
Breadcrumbs on pages from the toolbar lead to the "Advanced" area

### ISSUE THREAD

**Issue by tedbow** [contentacms/contenta_jsonapi#240]
In #60 the UI from Reservoir UI was brought in party to simplify the top level items.

![contenta_breadcrumbs](https://user-images.githubusercontent.com/132772/34062035-950841e8-e1b8-11e7-93f4-277aa923f943.png)

But here and in other pages from the toolbar the breadcrumbs lead to pages that aren't toolbar. So they expose links to areas the user didn't navigate from and to the "advanced" top level item.

Should breadcrumbs not appear on these pages at all? 

That way you would have to explicitly click "Advanced" to get to the "drupally" things

**Comment by e0ipso** [comment]
I think this is less of a thing in Contenta when compared with Reservoir. I'd like to keep the breadcrumbs, since they help with UX.

Do you think it's possible to have _intelligent_ breadcrumbs that reflect an _Advanced_ item in the pages that will land outside of the top level UI?

**Comment by e0ipso** [comment]
This is stale. I think that since we expose access to the advanced config this is OK.
