### ISSUE TITLE
get its own created content only thru Oauth2

### ISSUE THREAD

**Issue by angeenes** [contentacms/contenta_jsonapi#244]
Hi,

Trying to use the Oauth2 authentification thru my requests but I do not understand how to set up a role that will only display its own contents created ( I'm using Nuxt with waterWheel for infos ).

If a "user A" post some articles, I want him to be able, once authenticated, to see only its own contents ( from "user A" ).

I'm I thinking it correctly ? This is done thru authent with Oauth2 ? 
Can I fetch datas from one specific user once I know its ID ?

I did watch several tutorials videos about OAuth2 ( link to youtube [)](https://www.youtube.com/watch?v=rTcC0maPLSA&list=PLZOQ_ZMpYrZtqy5-o7KoDhM3n6M0duBjX) and learn A LOT of things, thanks, but can't get the all think, maybe this question is more related to how Drupal handles the roles, permissions, etc ...

**Comment by e0ipso** [comment]
> maybe this question is more related to how Drupal handles the roles, permissions, etc ...

Yes, that's the case. Please read the user guide in drupal.org, I think that will help.
