### ISSUE TITLE
Can I disable contentacms_enhancements?

### ISSUE THREAD

**Issue by simesy** [contentacms/contenta_jsonapi#245]
`contentacms_enhancements.module` contains a lot of cosmetic stuff it seems, and I think I'd like to disable it. Two years down the track I don't want someone to be struggling with a regression because Drupal was altered for cosmetic reasons. Like, it's pretty, but every change creates compound complexity.

I also don't find it very readable. If you look at [contenta_enhancements_toolbar_alter()](https://github.com/contentacms/contenta_jsonapi/blob/8.x-1.x/modules/contenta_enhancements/contenta_enhancements.module#L87-L354) there are 300 lines of toolbar alters, and no comments - why are these being altered? I can't tell without spending a lot of time working through the code.

Browsing around, I do see that ContentaEnhancementsServiceProvider.php is something I might actually want to keep - but perhaps that's just good practice...

What think you? Is this module required?

**Comment by simesy** [comment]
FYI I am testing it. When I turn off the enhancements, admin_toolbar started working!

**Comment by simesy** [comment]
Still dropping notes - my project is in a weird state where the profile is not installed, if I install it I get `You have requested a non-existent service "logger.channel.contentacms".`

**Comment by e0ipso** [comment]
@simesy thanks for leading this investigation. Whenever you are ready for PR I will be eager to review it.

**Comment by e0ipso** [comment]
Can you test if https://github.com/contentacms/contenta_jsonapi/compare/feat/245--allow-disable-contenta_enhancement?expand=1 works for this?
