### ISSUE TITLE
Protect API by Auth0 / JWT

### ISSUE THREAD

**Issue by kamalkech** [contentacms/contenta_jsonapi#246]
I am tired to find some examples to explain how we can protect the API by JWT or Auth0 or others, and i can't find any documentation about that (for contentacms).

there some helps here ?

**Comment by e0ipso** [comment]
You can check the documentation: http://cms.contentacms.io/help/tutorials

Thanks!

**Comment by kamalkech** [comment]
@e0ipso : i already check this list of tutorial but nothing, can you give me a exact link of article about what i need ??

thank you.

**Comment by e0ipso** [comment]
The OAuth2 articles will serve you. The Simple OAuth module uses JWT. Search in the issue queue for the module and you'll find more examples.
