### ISSUE TITLE
Material Admin theme breaks the db logging UI

### ISSUE THREAD

**Issue by arnoldbird** [contentacms/contenta_jsonapi#248]
In the Material Admin theme, at admin/reports/dblog, I can't find the button for clearing the database log.

My early impression of Contenta is that it is fantastic, but I don't know why it has its own theme.  By shipping with a custom theme, debugging is harder, because any bugs one encounters might be caused by the theme, and so the first thing the developer has to do is switch to a more standard Drupal theme like Seven to see if the theme is the culprit.  

Themes should be published as stand-alone extensions, not packaged with other software.  I prefer to use Contenta with the Seven theme. 

By the way, the Material Admin theme looks good.  It's a good theme, though it may need minor debugging.  But I don't think Contenta should ship with a custom theme.

**Comment by e0ipso** [comment]
Thanks for taking the rime to report!

> But I don't think Contenta should ship with a custom theme.

I disagree, I think that Material Admin brings much to the table. Besides, it seems that you can confirm that you are able to switch to another theme to your liking. At the end of the day one person likes a theme and another person likes another theme. Contenta CMS let's you choose your theme, you won't get that on many other decoupled CMS.

> By the way, the Material Admin theme looks good. It's a good theme, though it may need minor debugging.

Yeah! @briancwald has been tirelessly fixing all the minor bugs that people are reporting. If you provide a detailed report of what is wrong with the DB log UI, you'll get a fix :-)

**Comment by arnoldbird** [comment]
e0ipso,

Thanks for the prompt reply!  Material Admin should live on, but why should Contenta ship with a custom theme?  Is there a reason these two projects are combined?  Drupal allows for separation of business logic and presentation -- why not take advantage by separating Contenta from Material Admin?  

Contenta actually does not let me choose my theme, unless I'm willing to live with the PHP notices that result from switching to another theme.  I would like to switch to use another theme without triggering PHP notices.  Even though I can quiet the notices, they still fill up the db log and thus make the db log harder to use.

**Comment by e0ipso** [comment]
> Contenta actually does not let me choose my theme, unless I'm willing to live with the PHP notices that result from switching to another theme.

Ah that's a bug that should be fixed. Would you be willing to provide a PR for that?

**Comment by e0ipso** [comment]
> but why should Contenta ship with a custom theme?

We think that Material Admin is a big help for the UX. That's obviously subjective, but you still have the freedom to disagree *AND* change the theme.

**Comment by dawehner** [comment]
@arnoldbird 
We understand your frustration, software pretty much always sucks. I just had a couple of days fighting with webpack.

We as contenta want to provide a nice experience, documentation, some default content etc. 
As part of that having a "decoupled" looking admin theme is part of it. 
The other aspects, (the modules we install by default) is something you should learn out of contenta and then use in your own project. 

@arnoldbird Do you understand our reasoning a bit better now?

**Comment by arnoldbird** [comment]
@e0ipso 
What is a PR?  I have seen this term but I am not sure at the moment what it means.  Patch request?

@dawehner 
No frustration!  I'm thrilled to find these tools, and to see how mature it all is.  I can understand *why* you shipped with a theme, but I don't think your reasons are good, and I think it's a bad idea for multiple reasons:

1. If the theme provides functionality that can't be had without it, then you're breaking the logic/presentation divide.  If the theme does *not* provide functionality that can't be had without it -- that's good, but then you shouldn't ship with the theme.
2. It needs to be as evident as possible what Contenta adds to Drupal.  What's different.  What's the delta between this and simply installing Drupal.  The theme makes it harder to perceive that delta, which makes it harder to make initial decisions about starting my project.  Also, I find myself wondering, if they ship with a theme, does that mean they think that the project somehow does not have a reason-to-be without the theme? 
3. The first thing I need to do when I encounter a bug is deactivate the theme and turn on another theme to see if the bug is in the theme layer.  This makes it a little harder to evaluate your software initially.  It's just a few mouse clicks, but this all adds up.
4. A custom theme makes your distribution a little bigger.
5. Contenta and Material Admin are two different projects, and thus need two different project pages, release cycles, bug tracking, etc.
6. It creates a bit of doubt about how your team is functioning, because typically projects don't include things they shouldn't unless there is some kind of interpersonal dimension or communication issue.

Despite all of the above, Contenta and the associated modules are allowing me to make much, much faster progress on my project than I otherwise would.  And really I can't find any bugs except the one bug in the theme, and that's merely a PHP "notice."  Very minor!  Thanks

**Comment by arnoldbird** [comment]
On the other hand, if you feel like the custom theme helps you popularize/showcase Contenta, then maybe that's reason enough to include the theme.  From my perspective it does make me wonder if perhaps I should just install the underlying modules, and skip the distribution.  Though in any case, the distribution has made it very, very easy to see that decoupled Drupal can work well.  Contenta has that value, even if I end up not using the distribution and instead just installing and configuring the modules.

**Comment by arnoldbird** [comment]
@e0ipso
I remembered... PR = pull request.  Yes, I'll submit a PR.  Thx

**Comment by arnoldbird** [comment]
Closing this one.  I simply did not see the Delete link in the header.  The theme isn't broken.

**Comment by e0ipso** [comment]
> From my perspective it does make me wonder if perhaps I should just install the underlying modules, and skip the distribution.

The distribution provides both a collection of modules and some configuration. By starting that from scratch you'd be making an effort you are getting for free now. Even then it's technically possible.

**Comment by e0ipso** [comment]
> Closing this one. I simply did not see the Delete link in the header. The theme isn't broken.

Thanks for reporting @arnoldbird! Not many take the time to help improve :-)
