### ISSUE TITLE
Error loading node caused by contenta_enhancements_node_view_alter

### ISSUE THREAD

**Issue by kroawen** [contentacms/contenta_jsonapi#256]
Error
The website encountered an unexpected error. Please try again later.
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "simple_oauth.key.generator". in Drupal\Component\DependencyInjection\Container->get() (line 151 of core\lib\Drupal\Component\DependencyInjection\Container.php).
Drupal\Component\DependencyInjection\Container->get('simple_oauth.key.generator') (Line: 158)
Drupal::service('simple_oauth.key.generator') (Line: 39)
_contenta_jsonapi_generate_keys() (Line: 28)
contenta_jsonapi_install()
call_user_func_array('contenta_jsonapi_install', Array) (Line: 391)
Drupal\Core\Extension\ModuleHandler->invoke('contenta_jsonapi', 'install') (Line: 298)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1577)
install_install_profile(Array) (Line: 671)
install_run_task(Array, Array) (Line: 549)
install_run_tasks(Array) (Line: 117)
install_drupal(Object) (Line: 44)

**Comment by kroawen** [comment]
PHP 7.14 
APACHE 2.4

**Comment by e0ipso** [comment]
Did you install using composer?

**Comment by kroawen** [comment]
Yes， composer,
I try reinstall, when created  a new node,  it get a new error code:

The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Symfony\Component\Routing\Exception\ResourceNotFoundException</em>: No routes found for &quot;/node/85&quot;. in <em class="placeholder">Drupal\Core\Routing\Router-&gt;matchRequest()</em> (line <em class="placeholder">159</em> of <em class="placeholder">core/lib/Drupal/Core/Routing/Router.php</em>). <pre class="backtrace">Drupal\jsonapi\LinkManager\LinkManager-&gt;getRequestLink(Object) (Line: 136)
Drupal\jsonapi\Normalizer\Value\JsonApiDocumentTopLevelNormalizerValue-&gt;rasterizeValue() (Line: 178)
Drupal\jsonapi\Normalizer\JsonApiDocumentTopLevelNormalizer-&gt;normalize(Object, &#039;api_json&#039;, Array) (Line: 142)
Symfony\Component\Serializer\Serializer-&gt;normalize(Object, &#039;api_json&#039;, Array) (Line: 80)
Drupal\jsonapi\EntityToJsonApi-&gt;normalize(Object) (Line: 369)
contenta_enhancements_node_view_alter(Array, Object, Object) (Line: 501)
Drupal\Core\Extension\ModuleHandler-&gt;alter(&#039;node_view&#039;, Array, Object, Object) (Line: 285)
Drupal\Core\Entity\EntityViewBuilder-&gt;buildMultiple(Array) (Line: 220)
Drupal\Core\Entity\EntityViewBuilder-&gt;build(Array)
call_user_func(Array, Array) (Line: 378)
Drupal\Core\Render\Renderer-&gt;doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer-&gt;render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;Drupal\Core\Render\MainContent\{closure}() (Line: 582)
Drupal\Core\Render\Renderer-&gt;executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber-&gt;onViewRenderArray(Object, &#039;kernel.view&#039;, Object) (Line: 108)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher-&gt;dispatch(&#039;kernel.view&#039;, Object) (Line: 158)
Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object, 1, 1) (Line: 67)
Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap-&gt;handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle-&gt;handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache-&gt;pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache-&gt;handle(Object, 1, 1) (Line: 38)
Drupal\jsonapi\StackMiddleware\FormatSetter-&gt;handle(Object, 1, 1) (Line: 48)
Asm89\Stack\Cors-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware-&gt;handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware-&gt;handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel-&gt;handle(Object, 1, 1) (Line: 657)
Drupal\Core\DrupalKernel-&gt;handle(Object) (Line: 19)
</pre>

this is my site https://books.lovereadingbooks.com/v1/node/85

**Comment by e0ipso** [comment]
Is this a multisite install? Are you installing in a subdirectory? The installer seems to work under regular conditions.

**Comment by cmoeser** [comment]
Same here. Installing using Composer. No issues till the Drupal install screen. Then...

The website encountered an unexpected error. Please try again later.
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "simple_oauth.key.generator". in Drupal\Component\DependencyInjection\Container->get() (line 151 of core\lib\Drupal\Component\DependencyInjection\Container.php).
Drupal\Component\DependencyInjection\Container->get('simple_oauth.key.generator') (Line: 158)
Drupal::service('simple_oauth.key.generator') (Line: 39)
_contenta_jsonapi_generate_keys() (Line: 28)
contenta_jsonapi_install()
call_user_func_array('contenta_jsonapi_install', Array) (Line: 391)
Drupal\Core\Extension\ModuleHandler->invoke('contenta_jsonapi', 'install') (Line: 298)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1577)
install_install_profile(Array) (Line: 671)
install_run_task(Array, Array) (Line: 549)
install_run_tasks(Array) (Line: 117)
install_drupal(Object) (Line: 44)

**Comment by e0ipso** [comment]
After some fixes in the underlying modules this is now resolved.

Please do: `composer update --with-dependencies drupal/jsonapi_extras drupal/jsonapi`.
