### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by Memoyr** [contentacms/contenta_jsonapi#258]
Hi, 
I'm new with Drupal and I want to try Contenta as my goal is to build a decoupled Drupal 8 site.
I'm having issue with the installation.
When I look on under Installation here http://www.contentacms.org/  
and did install composer initially (globally though - not sure if it's good)
I encounter a problem at step 3 , where it says , install Drupal normally. 
On /core/install.php 
I get a multiple errors...

`Deprecated function: assert(): Calling assert() with a string argument is deprecated in Drupal\Core\Cache\MemoryBackend->set() (line 101 of core/lib/Drupal/Core/Cache/MemoryBackend.php).`

**Comment by Memoyr** [comment]
got it, I was using PHP 7.2.1 and should use 7.1

**Comment by e0ipso** [comment]
Great! Thanks for posting back with your solution.
