### ISSUE TITLE
simple oauth error

### ISSUE THREAD

**Issue by mdbadawi** [contentacms/contenta_jsonapi#259]
When i try to retrieve token  for the first time i get error 
{
    "error": "server_error",
    "message": "The authorization server encountered an unexpected condition which prevented it from fulfilling the request: You need to set the OAuth2 secret and private keys."
} 
and when i tried your demo site i got the same error 
using `curl -X POST -d "grant_type=password&client_id=0eecd0b9-b149-418f-b5ef-266b9aeeddab&client_secret=foobar&username=demo-user&password=demo-user" http://cms.contentacms.io/oauth/token` also the same error . thats why i issue this here not at simple oauth. thanks

**Comment by mdbadawi** [comment]
it's  key's files permission issue 
we fixed it in our project .Though you need to do so in your demo 
http://cms.contentacms.io/admin/api/authentication

**Comment by e0ipso** [comment]
Thanks for looping back to here.

**Comment by mattar88** [comment]
Hi, you should go to admin/config/people/simple_oauth and Generate Private and Public key
