### ISSUE TITLE
Error on install w/ jsonapi_extras module

### ISSUE THREAD

**Issue by emergencyofstate** [contentacms/contenta_jsonapi#261]
I followed the _Installation for Building Your Own Site_ steps via the readme and am getting this fatal error when Drupal installs.

`TypeError: Argument 3 passed to                                                                         [error]
Drupal\jsonapi_extras\ResourceType\ConfigurableResourceTypeRepository::__construct() must implement
interface Drupal\Core\Entity\EntityRepositoryInterface, instance of
Drupal\Core\Entity\EntityFieldManager given, called in
/www/contenta/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 282 in
Drupal\jsonapi_extras\ResourceType\ConfigurableResourceTypeRepository->__construct() (line 50 of
/www/contenta/web/modules/contrib/jsonapi_extras/src/ResourceType/ConfigurableResourceTypeRepository.php)`

May be related to this issue in the jsonapi_extras module?
https://www.drupal.org/project/jsonapi_extras/issues/2941481

I also see this pending patch within on jsonapi project page:
https://www.drupal.org/project/jsonapi/issues/2943795

Should I wait this one out?

**Comment by Memoyr** [comment]
same as mine 
https://github.com/contentacms/contenta_jsonapi/issues/260

**Comment by emergencyofstate** [comment]
I got passed this by installing the dev version of the jsonapi_extras module

https://www.drupal.org/project/jsonapi_extras/releases/8.x-1.x-dev

**Comment by Memoyr** [comment]
sorry for my ignorance, if you have time can you tell me what was the steps to install it ?
it is only like it's mention on the page ?
`Install with Composer: $ composer require 'drupal/jsonapi_extras:1.x-dev'`
and then I can do 
`composer create-project contentacms/contenta-jsonapi-project <DESTINATION> --stability dev --no-interaction
`
thanks

**Comment by emergencyofstate** [comment]
Hey. No problem! There may be a better/easier way but here's what I did:

1. Install project via composer
`composer create-project contentacms/contenta-jsonapi-project <DESTINATION> --stability dev --no-interaction && cd <DESTINATION>/web `

2. Before you move on to installing Drupal/Contenta install, update to the [8.x-1.x-dev](https://www.drupal.org/project/jsonapi_extras/releases/8.x-1.x-dev) version of the JSONAPI Extras module. Since Drupal isn't truly installed at this point you can't use drush to update so I had to physically swap out the jsonapi_extras folder within the modules/contrib folder

3. Proceed with the Drupal/Contenta install (in my case w/ mysql)
`../bin/drush si contenta_jsonapi --db-url=mysql://root:pass@localhost:3306/dbname -y`

**Comment by e0ipso** [comment]
I *just* tagged a release of JSON API Extras. This should be fixed. Please report if it's not.

**Comment by e0ipso** [comment]
Thanks for your contributions to the issue queue!!
