### ISSUE TITLE
JSON API full URL patch - Is it a sustainable approach?

### ISSUE THREAD

**Issue by szeidler** [contentacms/contenta_jsonapi#268]
Is there a reason, that the patch from https://www.drupal.org/node/2929600 is used in contentacms? As it is a BC breaking patch and marked as "Do not merge", I'm wondering if it is a sustainable approach or there for legacy reasons / by accident?

I just noticed the different behavior between two different projects, one with and one without the patch.

**Comment by e0ipso** [comment]
Hello @szeidler this is applied to maintain BC in Contenta CMS. Without this patch all consumers will have broken images.

**Comment by szeidler** [comment]
Thanks @e0ipso for the clarification :)
