### ISSUE TITLE
What is the proper way to update a Contenta CMS site project?

### ISSUE THREAD

**Issue by shrop** [contentacms/contenta_jsonapi#269]
What is the proper composer command to update a Contenta CMS project? I don't see this documented but have seen the following discussed:

* `composer update contentacms/contenta_jsonapi --with-dependencies`
* `COMPOSER_DISCARD_CHANGES=1 composer up --with-dependencies -o --prefer-dist`

I will be exporting my own config and adding modules. Looking for general guidance around these kinds of things in context of Contenta CMS. Love to see if anyone has info on this to make sure I am on the right track. Thanks!

**Comment by e0ipso** [comment]
This is intentionally not documented here. Contenta CMS is a _Fork & Go_ solution. There is no supported upgrade path. Use common Drupal update techniques instead.

**Comment by shrop** [comment]
Just catching up here. Thanks for that clarification @e0ipso!

**Comment by ghost** [comment]
I'm struggling trying to figure out how to update Drupal core in Contenta. So far nothing I've tried has worked so I'm stuck on 8.5.3 while 8.6.1 is most current. Any suggestions on where to look further?

**Comment by ghost** [comment]
I finally figured it out. I used the Composerize module to generate a composer.json file and then updated the required version of Drupal in composer.json and everything seems to be working great.

**Comment by matgianesini** [comment]
Hello everyone! I spent a whole day trying to figure out how to update Contenta using composer, and something quite simple just worked for me:

The main question for me as a composer noob was... how can composer update drupal/core when that is not included in Contenta's composer.json file? I'm guessing the composerize module, proposed above, solves exactly that. Still, in my case I couldn't get it to work that way.

In the end it seems this was all I needed:
`composer update drupal/core webflo/drupal-core-require-dev --with-dependencies`

All green checks on my Contenta now. I know `--with-dependencies` is regarded as poor form in composer and drupal circles... but other than that, any of you know if there's anything wrong with this simple one liner?

**Comment by BrianGilbert** [comment]
@matgianesini I usually just do `composer remove drupal/core` and it automatically get reinstalled with the latest version because it's a dependency
