### ISSUE TITLE
You have requested a non-existent service "simple_oauth.key.generator"

### ISSUE THREAD

**Issue by zkoncir** [contentacms/contenta_jsonapi#270]
I realize this issue has been reported before, but I cannot get passed it. I'm using a fresh install, php 7.1.13

Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                                                     [ok]
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "simple_oauth.key.generator". in                                             [error]
/home/ec2-user/contentacms/web/core/lib/Drupal/Component/DependencyInjection/Container.php:151
Stack trace:
#0 /home/ec2-user/contentacms/web/core/lib/Drupal.php(158): Drupal\Component\DependencyInjection\Container->get('simple_oauth.ke...')
#1 /home/ec2-user/contentacms/web/profiles/contrib/contenta_jsonapi/contenta_jsonapi.install(39): Drupal::service('simple_oauth.ke...')
#2 /home/ec2-user/contentacms/web/profiles/contrib/contenta_jsonapi/contenta_jsonapi.install(28): _contenta_jsonapi_generate_keys()
#3 [internal function]: contenta_jsonapi_install()
#4 /home/ec2-user/contentacms/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(391): call_user_func_array('contenta_jsonap...', Array)
#5 /home/ec2-user/contentacms/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(298): Drupal\Core\Extension\ModuleHandler->invoke('contenta_jsonap...', 'install')
#6 /home/ec2-user/contentacms/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, false)
#7 /home/ec2-user/contentacms/web/core/includes/install.core.inc(1577): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, false)
#8 /home/ec2-user/contentacms/web/core/includes/install.core.inc(671): install_install_profile(Array)
#9 /home/ec2-user/contentacms/web/core/includes/install.core.inc(549): install_run_task(Array, Array)
#10 /home/ec2-user/contentacms/web/core/includes/install.core.inc(117): install_run_tasks(Array)
#11 /home/ec2-user/contentacms/vendor/drush/drush/includes/drush.inc(727): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#12 /home/ec2-user/contentacms/vendor/drush/drush/includes/drush.inc(712): drush_call_user_func_array('install_drupal', Array)
#13 /home/ec2-user/contentacms/vendor/drush/drush/commands/core/drupal/site_install.inc(82): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array)
#14 /home/ec2-user/contentacms/vendor/drush/drush/commands/core/site_install.drush.inc(255): drush_core_site_install_version('contenta_jsonap...', Array)
#15 /home/ec2-user/contentacms/vendor/drush/drush/includes/command.inc(422): drush_core_site_install('contenta_jsonap...')
#16 /home/ec2-user/contentacms/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#17 /home/ec2-user/contentacms/vendor/drush/drush/includes/command.inc(199): drush_command('contenta_jsonap...')
#18 /home/ec2-user/contentacms/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#19 /home/ec2-user/contentacms/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#20 /home/ec2-user/contentacms/vendor/drush/drush/drush.php(12): drush_main()
#21 {main}

**Comment by e0ipso** [comment]
Did the project fail to install?

**Comment by e0ipso** [comment]
I will close this since I have been able to successfully install Contenta several times without this problem. Please feel free to request a re-open if this issue persists with the lastest code.

**Comment by rafatwork** [comment]
Getting the exact same error unfortunately. Tried installing using drush si as well as via the browser, same result.

**Comment by drupdotes** [comment]
Same error here, but I'm using a custom updated example-drops-8-composer:dev-contenta repo on Pantheon (php 7.2).

**Comment by justinlevi** [comment]
@e0ipso I'm seeing the same issue here as well using docksal on Windows using the composer install command below:

```
composer create-project contentacms/contenta-jsonapi-project MYPROJECT --stability dev --no-interaction
```


From:
http://www.contentacms.org


`Composer version 1.6.5 2018-05-04 11:44:59`

Here's my composer.lock require object:

```
 "require": {
                "composer/installers": "^1.0.24",
                "cweagans/composer-patches": "^1.6.0",
                "drupal/admin_toolbar": "^1.23",
                "drupal/consumer_image_styles": "^2.0@rc",
                "drupal/consumers": "^1.0@beta",
                "drupal/core": "^8.5.3",
                "drupal/decoupled_router": "^1.0@rc",
                "drupal/dropzonejs": "^2.0@alpha",
                "drupal/entity_browser": "^2.0@alpha",
                "drupal/fieldable_path": "^1.0",
                "drupal/graphql": "^3.0@beta",
                "drupal/image_widget_crop": "^2.1",
                "drupal/inline_entity_form": "^1.0@beta",
                "drupal/jsonapi": "^1.16",
                "drupal/jsonapi_extras": "^2.0",
                "drupal/jsonrpc": "^1.0@alpha",
                "drupal/material_admin": "1.x-dev",
                "drupal/media_entity_browser": "^2.0@alpha",
                "drupal/openapi": "^1.0@alpha",
                "drupal/schemata": "^1.0@alpha",
                "drupal/simple_oauth": "^3.3",
                "drupal/subrequests": "^2.0@rc",
                "drupal/video_embed_field": "^2.0"
            },
```

And the specific section for simple_oauth:
```
 {
            "name": "drupal/simple_oauth",
            "version": "3.8.0",
            "source": {
                "type": "git",
                "url": "https://git.drupal.org/project/simple_oauth",
                "reference": "8.x-3.8"
            },
            "dist": {
                "type": "zip",
                "url": "https://ftp.drupal.org/files/projects/simple_oauth-8.x-3.8.zip",
                "reference": "8.x-3.8",
                "shasum": "dfc531971c23c409b514eba28cd050dd8f1277f2"
            },
            "require": {
                "drupal/consumers": "^1.0.0-beta3",
                "drupal/core": "^8.3",
                "league/oauth2-server": "~6.0"
            },
            "type": "drupal-module",
            "extra": {
                "branch-alias": {
                    "dev-3.x": "3.x-dev"
                },
                "drupal": {
                    "version": "8.x-3.8",
                    "datestamp": "1525410485",
                    "security-coverage": {
                        "status": "covered",
                        "message": "Covered by Drupal's security advisory policy"
                    }
                }
            },
            "notification-url": "https://packages.drupal.org/8/downloads",
            "license": [
                "GPL-2.0+"
            ],
            "authors": [
                {
                    "name": "Mateu Aguiló Bosch",
                    "homepage": "https://www.drupal.org/user/550110",
                    "email": "mateu.aguilo.bosch@gmail.com"
                },
                {
                    "name": "pcambra",
                    "homepage": "https://www.drupal.org/user/122101"
                }
            ],
            "description": "The Simple OAuth module for Drupal",
            "homepage": "https://www.drupal.org/project/simple_oauth",
            "support": {
                "source": "http://cgit.drupalcode.org/simple_oauth"
            }
        }
```

I've tried running the following: 

$ `composer clear-cache`
as well as 
$ `composer update --with-dependencies drupal/jsonapi_extras drupal/jsonapi` 

Still seeing the same issue. 


Reference issues:
https://github.com/contentacms/contenta_jsonapi/issues/228
https://github.com/contentacms/contenta_jsonapi/issues/256

**Comment by zkoncir** [comment]
Sorry I should have provided more context, I was attempting to use Amazon Linux and the project was failing to install. I switched to Ubuntu 16 and all works smoothly.

**Comment by cmoeser** [comment]
Same error using the composer install. 
![error](https://user-images.githubusercontent.com/2686223/43460800-b59b1a1c-949f-11e8-9e69-d775db4b900c.jpg)

**Comment by e0ipso** [comment]
@cmoeser it seems that this is environmental, as per https://github.com/contentacms/contenta_jsonapi/issues/270#issuecomment-407740496. Can you share your environment?

**Comment by cmoeser** [comment]
@e0ipso Sorry should have included, happening on 3 machines. Environments as follows:
1) Windows 10
Composer 1.5.2
xampp/mariadb/php 7.2.5

2) Windows 10
Composer 1.6.5
xamp/mariadb/php 7.2.5

3) Windows 8
Composer 1.6.5
IIS7/MySQL 6.3/php 7.1.2

**Comment by benedikt-buchert** [comment]
Having the same issue following these instructions: https://thinktandem.io/blog/2019/01/25/lando-contenta-cms-nuxt-pt-1/ Not sure how to resolve. 

Tried:
```
lando composer clear-cache
lando composer install --prefer-source
```
 simple oauth version according to lock file:
> "name": "drupal/simple_oauth",
> "version": "4.3.0",

**Comment by benedikt-buchert** [comment]
Finally worked after  deleting the modules and reinstalling.
