### ISSUE TITLE
Installer fails with missing Media module

### ISSUE THREAD

**Issue by acy76** [contentacms/contenta_jsonapi#274]
Attempting to install in Vagrant (box is https://github.com/Lullabot/trusty32-lamp, using PHP7) using either the "Quick Install" or "Installation for Building Your Own Site" steps as outlined in the README results in a failure, "Unable to install the Media Entity Browser module since it requires the Media module".

Am I making a mistake here or is this a legitimate installer bug?

<img width="1018" alt="screen shot 2018-04-17 at 9 39 40 am" src="https://user-images.githubusercontent.com/1123220/38877004-552b1188-4223-11e8-8bff-9fab908dd961.png">

**Comment by readingdan** [comment]
I am getting the same when trying to install. Using Wodby's docker-compose v 2.x.

![screen shot 2018-04-18 at 16 44 22](https://user-images.githubusercontent.com/35099463/38986104-50a715e8-43c3-11e8-9ae1-6550e568e4fa.png)

**Comment by e0ipso** [comment]
Thanks for the report. I hope to have a fix for this soon.

**Comment by e0ipso** [comment]
Hopefully this will fix the issue: https://github.com/contentacms/contenta_jsonapi/commit/5a3069ab93c07ffcdc3d45b24ba6c13bfb572463 (just re-download / install the latest version of Contenta).

Let me know if it doesn't and I will re-open this issue.

**Comment by antonia-rose** [comment]
worked for me. thanks a lot for this fast fix.

@readingdan can you tell me how you use contenta with docker? would like to use that too, but didn't find anything about it
