### ISSUE TITLE
PHP Fatal Error when running Drush in a fresh install of Contenta

### ISSUE THREAD

**Issue by simonhunt** [contentacms/contenta_jsonapi#275]
Contenta Version: dev-8.x-1.x
OS: Mac OS High Sierra

After a fresh install of Contenta I get this error when trying to run Drush:

    PHP Fatal error:  Cannot redeclare composerRequire550c9a6ce03af1d776fb6bc79635f0ca( (previously declared in /Users/simon/Code/exp/contenta/vendor/composer/autoload_real.php:63) in /Users/simon/code/exp/contenta/vendor/composer/autoload_real.php on line 70

    Fatal error: Cannot redeclare composerRequire550c9a6ce03af1d776fb6bc79635f0ca() (previously declared in /Users/simon/Code/exp/contenta/vendor/composer/autoload_real.php:63) in /Users/simon/code/exp/contenta/vendor/composer/autoload_real.php on line 70
    Drush command terminated abnormally due to an unrecoverable error.   [error]
    Error: Cannot redeclare composerRequire550c9a6ce03af1d776fb6bc79635f0ca() (previously
declared in
    /Users/simon/Code/exp/contenta/vendor/composer/autoload_real.php:63) in /Users/simon/code/exp/contenta/vendor/composer/autoload_real.php, line 70

It seems that the Autoload file may be included twice leading to the redeclaration error. I'm happy to help work on a pull request to fix this if it is a bug, but I'm not really sure where to start.

Can anyone help?

**Comment by e0ipso** [comment]
I am not able to reproduce this. Is this something that went away after a second try?

**Comment by e0ipso** [comment]
I have been installing Contenta successfully multiple times recently. Please request a re-open if necessary.

**Comment by simonhunt** [comment]
I figured this out.

The error occurs when running drush from within the web folder using `../bin/drush`.

When running drush from outside the web folder using `./bin/drush` everything works fine.

**Comment by e0ipso** [comment]
Thanks for taking the time to loop back into this.
