### ISSUE TITLE
Switch to media in core

### ISSUE THREAD

**Issue by marcoscano** [contentacms/contenta_jsonapi#276]
Since 8.4.0 Drupal core has media support (by moving an improved version of Media Entity into core). By now most contributed modules that interacted previously with the contrib Media Entity module have branches that support working with the media-in-core approach. Contenta however still ships with the Media Entity approach, and it would be good to convert it to use the new media-in-core approach.

**Long version:**
The change record indicates everything that needs to be done: https://www.drupal.org/node/2863992

**Abbreviated version:**
In our case, that translates mainly into:
- Update `composer.json` to remove Media Entity and add Media (core).
- Update `composer.json` to pull all contrib dependencies with their new branches (Entity Browser, Media Entity Image, DropzoneJS, Media Entity Browser, etc.). Do the same to all custom module .info.yml files that declare dependencies on Media Entity, Media Entity Document or Media Entity Image.
- Rename config entities shipped by us (for example `media_entity.bundle.image` becomes `media.type.image` ). Check also other config entities that could depend on those (like field storage, fields, etc).
- Check if custom modules or other config entities (such as views, etc) have dependencies on the "Media Entity" contrib module. Replace them by the "Media" module instead.
- Due to the renaming of the bundle from "Bundle" to "Type", depending on our CSS we might need to adjust some selectors, if we were relying on markup that changed (not likely, but I've seen it happen).
- Check all custom code that interacts with media entities, and verify if we are using any of the methods that were renamed / replaced.
- Update the tests, if any.

**Comment by e0ipso** [comment]
I want to print this issue and frame it in my office. This looks perfect. Thanks @marcoscano!

**Comment by e0ipso** [comment]
This was worked on and committed to the latest version. Thanks for the report!
