### ISSUE TITLE
Cannot load /admin/api page after fresh install

### ISSUE THREAD

**Issue by pascal-kubrick** [contentacms/contenta_jsonapi#286]
I've installed the project using composer and ran drush si, but cannot access the /admin/api page (loader keeps spinning). Opening the developer console shows a 404 error to /openapi/jsonapi

Opening the 404 link in the browser diaplays the following error:

`The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Drupal\Component\Plugin\Exception\PluginNotFoundException</em>: The &quot;&quot; entity type does not exist. in <em class="placeholder">Drupal\Core\Entity\EntityTypeManager-&gt;getDefinition()</em> (line <em class="placeholder">133</em> of <em class="placeholder">core/lib/Drupal/Core/Entity/EntityTypeManager.php</em>). <pre class="backtrace">Drupal\openapi\OpenApiGenerator\OpenApiGeneratorBase-&gt;includeEntityTypeBundle(Array, NULL, NULL) (Line: 32)
Drupal\openapi\OpenApiGenerator\OpenApiJsonapiGenerator-&gt;getPaths(Array) (Line: 91)
Drupal\openapi\OpenApiGenerator\OpenApiGeneratorBase-&gt;getSpecification(Array) (Line: 50)
Drupal\openapi\Controller\ApiSpecificationControllerBase-&gt;getSpecification()
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber-&gt;Drupal\Core\EventSubscriber\{closure}() (Line: 582)
Drupal\Core\Render\Renderer-&gt;executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber-&gt;wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber-&gt;Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object, 1, 1) (Line: 67)
Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap-&gt;handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle-&gt;handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache-&gt;pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache-&gt;handle(Object, 1, 1) (Line: 40)
Drupal\jsonapi\StackMiddleware\FormatSetter-&gt;handle(Object, 1, 1) (Line: 49)
Asm89\Stack\Cors-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware-&gt;handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware-&gt;handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel-&gt;handle(Object, 1, 1) (Line: 664)
Drupal\Core\DrupalKernel-&gt;handle(Object) (Line: 19)
</pre>`

**Comment by violabg** [comment]
Same here

**Comment by e0ipso** [comment]
This may mean that the installation was corrupted. Did you succeed after this, or did you give up instead?

**Comment by pascal-kubrick** [comment]
Seemed to be fine now after trying a fresh install (despite trying this several times last time). I'm not sure what's changed.

Thanks for the great work!
