### ISSUE TITLE
Is graphql supported yet? 

### ISSUE THREAD

**Issue by violabg** [contentacms/contenta_jsonapi#291]
I thought that graphQL was already available thanks to #195, but when I try to enable it, by clicking the button on page /admin/api/advanced, it says:

GraphQL is still in development, sorry!

**Comment by e0ipso** [comment]
Yes! GraphQL is supported. The page you are looking at is outdated and should be removed. I created https://github.com/contentacms/contenta_jsonapi/issues/302 for that.

Enable the GraphQL module normally in /admin/modules

Thanks for reaching out!
