### ISSUE TITLE
Cannot translate

### ISSUE THREAD

**Issue by x7ian** [contentacms/contenta_jsonapi#292]
Hello, im trying to translate contenta CMS to Spanish.
I installed spanish at Configuration > Regional and language > Languages and set it as default languaje.
However im not able to find the  Available Translation Updates section at Reports > Available Translation Updates (admin/reports/translations).
That page doesnt exist. The docs (https://www.drupal.org/docs/8/multilingual/install-a-language) say that if you don't have that link you might need to enable the "Update manager" module.
I go to extend and check for that module and it is installed.
What could be missing in order to translate the cms?
Thank you for your help!

**Comment by wimleers** [comment]
Thanks for trying to contribute to Contenta! Sorry to hear you got stuck :(

Did you also install the "Interface Translation" module? That is necessary to translate Contenta's interface text.
