### ISSUE TITLE
Cant find the Flush cache link

### ISSUE THREAD

**Issue by x7ian** [contentacms/contenta_jsonapi#293]
Hello, Drupal usually has some Flush Cache links under the first item of on the administration menu.
The idea is to have access to a direct link and not to have to go to Admin > Config > development > performance to click the Flush Cache button.
Not showing on Contenta CMS.
How can i enable this?

**Comment by wimleers** [comment]
You shouldn't need to flush caches; if you see something stale, that's a bug.

Why do you want/need to flush caches?

**Comment by e0ipso** [comment]
While @wimleers' question is very valid, I want to note that you can find the link here:

<img width="558" alt="2018-07-21 08-59-45" src="https://user-images.githubusercontent.com/1140906/43033129-9ca74158-8cc4-11e8-8715-0838ac0df7ba.png">
