### ISSUE TITLE
Api schema data not displayed in /admin/api

### ISSUE THREAD

**Issue by vermario** [contentacms/contenta_jsonapi#294]
Hello!

this issue can be related to issue #286 , but the symptom is different so I thought I'd report it separately.

I installed via composer the latest version, but when I visit `/admin/api`, the swagger interface loads up and appears, but it only shows a list of the entity types, but no data about them.

It looks like this:

![image](https://user-images.githubusercontent.com/185412/40889282-9161fb80-676c-11e8-9519-2ffa39bca024.png)

The console does not display any error. Here's the combination of modules I have at the moment:

```
Admin Toolbar 8.x-1.24 Includes: Admin Toolbar
--
Consumer Image Styles 8.x-2.0-rc5 Includes: Consumer Image Styles
Consumers 8.x-1.0-beta3 Includes: Consumers
dropzonejs 8.x-2.0-alpha3 Includes: DropzoneJS entity browser widget, dropzonejs
Entity Browser 8.x-2.0-alpha2 Includes: Entity Browser, Entity Browser IEF
Fieldable Path 8.x-1.0-rc4 Includes: Fieldable Path
GraphQL 8.x-3.0-beta8 Includes: GraphQL, GraphQL Core
Inline Entity Form 8.x-1.0-rc1 Includes: Inline Entity Form
JSON API 8.x-1.19 Includes: JSON API
JSON API Extras 8.x-2.1 Includes: JSON API Extras
JSON-RPC 8.x-1.0-alpha7 Includes: JSON-RPC 2.0, JSON-RPC 2.0 Discovery
Media Entity Browser 8.x-2.0-alpha1 Includes: Media Entity Browser
OAuth 2.0 8.x-3.8 Includes: Simple OAuth, Simple OAuth Extras
OpenAPI 8.x-1.0-alpha1 Includes: OpenAPI, OpenAPI Redoc Documentation
Schemata 8.x-1.0-alpha3 Includes: Schemata, Schemata in JSON Schema
Subrequests 8.x-2.0-rc3 Includes: Subrequests
```

I tried to copy-paste the content of the file into the online swagger.io, and there it complains about validation errors, here's the screenshot:

![image](https://user-images.githubusercontent.com/185412/40889323-603d1840-676d-11e8-8e43-fc14ad9ff8ef.png)

Any idea on where I could start looking to fix this, or where the issue might be? I'd be happy to collaborate to fix it.

**Comment by vermario** [comment]
Hello, I found out what the issue is. Basically, we need to switch to the -dev version of the openapi module (https://www.drupal.org/project/openapi) (the version used here is a year old), and then adapt the code in `/modules/contenta_enhancements/src/Controller/OpenApiDocs.php` to work with the new route that is introduced by the new version of the openapi module.

**Comment by e0ipso** [comment]
That's fantastic investigation!

I have logged all the errors in the Swagger editor and they look legit bugs. I'll make sure those are followed up appropriately.

Will you be sending a PR to fix this?

**Comment by vermario** [comment]
@e0ipso I will try :-) what is the best practice regarding including -dev versions of modules however?

**Comment by e0ipso** [comment]
@vermario this should go as a `-dev` dependency using composer in the distribution's `composer.json`.

**Comment by vermario** [comment]
There you go :)

**Comment by e0ipso** [comment]
This should be fixed now.
