### ISSUE TITLE
Media core related: Install fails to copy a few files and some actions are reported missing

### ISSUE THREAD

**Issue by shrop** [contentacms/contenta_jsonapi#298]
During install, before entering site admin user credentials and email address, I get the following errors.

```
The specified file core/modules/media/images/icons/no-thumbnail.png could not be moved/copied because the destination directory is not properly configured. This may be caused by a problem with file or directory permissions. More information is available in the system log.

The specified file core/modules/media/images/icons/video.png could not be moved/copied because the destination directory is not properly configured. This may be caused by a problem with file or directory permissions. More information is available in the system log.

The specified file core/modules/media/images/icons/generic.png could not be moved/copied because the destination directory is not properly configured. This may be caused by a problem with file or directory permissions. More information is available in the system log.

The specified file core/modules/media/images/icons/audio.png could not be moved/copied because the destination directory is not properly configured. This may be caused by a problem with file or directory permissions. More information is available in the system log.

Unexpected error during import with operation create for system.action.media_delete_action: The "media_delete_action" plugin does not exist.

Unexpected error during import with operation create for system.action.media_publish_action: The "media_publish_action" plugin does not exist.

Unexpected error during import with operation create for system.action.media_save_action: The "media_save_action" plugin does not exist.

Unexpected error during import with operation create for system.action.media_unpublish_action: The "media_unpublish_action" plugin does not exist.
```

Related (I think), I noted the following config that needs importing following installation at /admin/config/development/configuration:

```
system.action.media_unpublish_action
system.action.media_save_action
system.action.media_publish_action
system.action.media_delete_action
```

They are new files for import

I am not sure the best way to tell the version I am running, but I did the composer create at `Thu Jun 21 23:15:42 2018 -0400`. contenta_jasonapi is running a dev release.

This could very well be a core issues with the media in core work. I am not sure it is really an issue, but noting in case others noticed the same thing. I haven't found the exact issue cited in the core issue queue yet, but I did find something possibly related in the lightning distro queue: https://www.drupal.org/project/lightning_media/issues/2968214

**Comment by shrop** [comment]
When attempting import, the files do not exist:

```
Unexpected error during import with operation create for system.action.media_delete_action: The "media_delete_action" plugin does not exist.
Unexpected error during import with operation create for system.action.media_publish_action: The "media_publish_action" plugin does not exist.
Unexpected error during import with operation create for system.action.media_save_action: The "media_save_action" plugin does not exist.
Unexpected error during import with operation create for system.action.media_unpublish_action: The "media_unpublish_action" plugin does not exist.
```

**Comment by shrop** [comment]
I did some additional research and here is what I found:

* The updated media actions were made in this PR: https://github.com/contentacms/contenta_jsonapi/pull/281/commits/144f28573e67cb4d80651f2c82ab160c4c5bbe15
* I found this as part of the contrib media_entity updat eto media in core: https://www.drupal.org/project/media_entity_actions

> Generic entity actions will be added to core in 8.6.x, at which point this module will become obsolete and an upgrade path, if needed, will be provided. See #2916740: Add generic entity actions and #2670730: Provide a delete action for each content entity type for more information.

So I am thinking that we could add media_entity_actions to Contenta and then remove it once Contenta is upgraded to 8.6.x. On the other hand, we could just remove the the four config files from Contenta since the contenta_jsonapi profile isn't updated once used for install per https://github.com/contentacms/contenta_jsonapi/issues/269#issuecomment-374514425

**Comment by shrop** [comment]
The PR I submitted actually just removes the media action config files from the contenta_jsonapi profile. I don't think they are needed and Drupal core 8.6.x will add them back form a core perspective.

**Comment by shrop** [comment]
I believe that the generic icons that are not copying over may be a files permissions issue in my environment (Drupal4Docker). I will open a new separate issue if I find that to not be the case and get more details on this one.

**Comment by Rar9** [comment]
any update fix/patch  on this issue that still appears on a fresh install ... with version Drupal 9.29
