### ISSUE TITLE
[IDEA] Implement a IONIC native app

### ISSUE THREAD

**Issue by dawehner** [contentacms/contenta_jsonapi#30]
https://www.drupal.org/u/samuelmortenson offered to get involved with an ionic native app.
That's great, as for example, the more frontends we have, the better it gets for other frontends, as we will explore the potential problems

It would be great if samuel mortenson could come up with general ideas how this native app would look like, which features it could provide etc.

**Comment by e0ipso** [comment]
I am closing this one, as I'm about to create the `contenta_ionic` repo!  🎉
