### ISSUE TITLE
What is the purpose of the json api documentation page

### ISSUE THREAD

**Issue by mminklet** [contentacms/contenta_jsonapi#300]
Edit: Never mind, I updated and it's all there!

**Comment by e0ipso** [comment]
Thanks for taking the time to loop back.

**Comment by mminklet** [comment]
Hey @e0ipso  I updated again and it only works with the dummy content, otherwise it's completely blank. Tbh I don't understand what is supposed to happen, or how it's supposed to be used. Is there any documentation on setting this up? The api itself works. 

I made a fresh installation, deleted the recipes content, created new content types and content, and now there is nothing in the admin/api. No js errors, nothing unusual in the network tab.

**Comment by e0ipso** [comment]
@MichaelMallett can you share your content types? It seems that the schema is failing to be generated for those.

**Comment by mminklet** [comment]
They're fairly basic, an article and an event content type with the following fields

https://imgur.com/mQtS1AY

https://imgur.com/a/5RkP7Iz


The api page just looks like this. I've no idea what it's supposed to do and there are no error messages
https://imgur.com/a/mhPluYB

It would be really useful if it said _something_

**Comment by mminklet** [comment]
What might be related is that if I try to go to the download api documentation link, I get the following error for openapi/jsonapi?_format=json

Error: Call to a member function getEntityTypeId() on null in Drupal\openapi\Plugin\openapi\OpenApiGenerator\JsonApiGenerator->getPaths() (line 157 of modules/contrib/openapi/src/Plugin/openapi/OpenApiGenerator/JsonApiGenerator.php).

**Comment by mminklet** [comment]
Also, slightly related, the latest openapi module splitting of openapi_redoc causes these errors, which I can't do anything about.

Is this related?

The following module is missing from the file system: openapi_redoc bootstrap.inc:268

I'm really really trying to use contenta but it's been one hassle after another if I'm totally honest.

**Comment by e0ipso** [comment]
Ah, this is most probably a problem with your particular site. I see this working in the out of the box installation.

Did you reinstall Contenta recently?

**Comment by mminklet** [comment]
As I said, I did a fresh install. I had to because the openapi redoc problem here:
https://www.drupal.org/project/lightning_api/issues/2996108

Completely wrecked my site. 

I've not done anything special here, I've created some basic content types.

**Comment by mminklet** [comment]
@e0ipso What do you mean exactly as you see it working in the out of the box installation?

**Comment by mminklet** [comment]
So now, completely new installation with no demo content. Create a new article content type with a body field. I still get this and nothing on the api page (tho a loading gif this time)

```
Call to a member function getEntityTypeId() on null in <em class="placeholder">Drupal\openapi\Plugin\openapi\OpenApiGenerator\JsonApiGenerator-&gt;getPaths()</em> (line <em class="placeholder">157</em> of <em class="placeholder">modules/contrib/openapi/src/Plugin/openapi/OpenApiGenerator/JsonApiGenerator.php</em>). <pre class="backtrace">Drupal\openapi\Plugin\openapi\OpenApiGenerator\JsonApiGenerator-&gt;getPaths() (Line: 213)
Drupal\openapi\Plugin\openapi\OpenApiGeneratorBase-&gt;getSpecification() (Line: 39)
```

Am I supposed to do something?

**Comment by phalconVee** [comment]
Hi @MichaelMallett please did you later find a fix for this

`Error: Call to a member function getEntityTypeId() on null in Drupal\openapi\Plugin\openapi\OpenApiGenerator\JsonApiGenerator->getPaths() (line 157 of modules/contrib/openapi/src/Plugin/openapi/OpenApiGenerator/JsonApiGenerator.php).`
