### ISSUE TITLE
Installation Configuration validation

### ISSUE THREAD

**Issue by danharper83** [contentacms/contenta_jsonapi#307]
I ran the composer command as per the website

`composer create-project contentacms/contenta-jsonapi-project MYPROJECT --stability dev --no-interaction`

When I run through the install I get the following error message and it does not continue

> Unable to install the openapi_redoc module since it does not exist.

**Comment by felubra** [comment]
I’m having the same problem.

**Comment by felubra** [comment]
Seems that the openapi_redoc submodule was removed in the latest release of drupal/openapi (8.x-1.0-beta2), [released July, 25](https://www.drupal.org/project/openapi/releases/8.x-1.0-beta2) - [issue 2948570](https://www.drupal.org/project/openapi/issues/2948570) fix.

**Comment by felubra** [comment]
**Workaround:** remove the entry 'openapi_redoc: 0' (line 44) in web/profiles/contrib/contenta_jsonapi/config/sync/core.extension.yml

**Comment by e0ipso** [comment]
Thanks for reporting. This is an issue introduced by a dependency, as note by @felubra in https://github.com/contentacms/contenta_jsonapi/issues/307#issuecomment-408286510.

There is an incoming fix.
