### ISSUE TITLE
Suggeting a Tutorial ; Gatsby JS: A Powerful Front End Tool for Decoupled Devs

### ISSUE THREAD

**Issue by akirby310** [contentacms/contenta_jsonapi#310]
Hello - Recommending this new video on Gatsby.js for decoupled developers. Hope it makes it! 
https://www.mediacurrent.com/videos/gatsby-js-powerful-front-end-tool-decoupled-devs/

Thanks!

Adam

This presentation covers some of the main benefits that you or your team could experience with Gatsby:

Fast - It really, really is
Flexible- Bring your data from wherever
 Full Drupal, headless, REST APIs, local filesystem, Gatsby handles it all with GraphQL.
Fun - The most fun I've had building a site since I first learned React
 
Look at the best (and a few not so best) use cases for having Gatsby:

Most public facing sites (vs. logged-in portion)
Brochure sites
Blogs
 
Plus:

What Gatsby's GraphQL data layer is and how and why to embrace it
Gatsby's internal API for building a Gatsby starter to fit your team
Looking at Gatsby's plugin/source/transformer system for taking Gatsby from a blog-generator to a site-generator

**Comment by e0ipso** [comment]
Thanks for this contribution, sorry for taking so long to fix it.
