### ISSUE TITLE
API Warnings, no type specified

### ISSUE THREAD

**Issue by mminklet** [contentacms/contenta_jsonapi#320]
Completely new installation, fresh install, new basic content type.

`No "type" specified at "/definitions/media--image/properties/data". Automatically detected: "object"
No "type" specified at "/definitions/node--article/properties/data". Automatically detected: "object"
No "type" specified at "/definitions/taxonomy_term--article_type/properties/data". Automatically detected: "object"`

Similar to my other tickets, I don't actually know where to start with this because the documentation is a bit all over the place.

**Comment by mminklet** [comment]
It would be really helpful to give some indication where to start looking with this.  Is this ticket related?

https://github.com/Rebilly/ReDoc/issues/254

**Comment by e0ipso** [comment]
This seems to be an issue with either https://www.drupal.org/project/schemata or https://www.drupal.org/project/openapi. Can you create a bug report to either one of these projects?

It is safe to ignore.
