### ISSUE TITLE
Why core version is still 8.6.0@beta?

### ISSUE THREAD

**Issue by alexey-kuznetsov** [contentacms/contenta_jsonapi#322]
It should be updated to 8.6.1.

**Comment by e0ipso** [comment]
Due to semantic versioning you'll get the same version. Is there any other specific reason to make this change?

**Comment by alexey-kuznetsov** [comment]
There are annoying errors in status report. And also I suppose, that notifications about it could be sent by email and make some people worry.

**Comment by e0ipso** [comment]
@alexey-kuznetsov can you share a screenshot of the error in the status report? You should get `8.6.1` downloaded by Composer, which is what `^8.6.0@beta` resolves to (as of today).

**Comment by alexey-kuznetsov** [comment]
Just copied this from status report:
```
Drupal Version
8.6.0-beta1
```
And I see this warning.
`Not secure! (version 8.6.1 available)`

I suppose it happens because latest release 8.6.1 is newer than any beta.

**Comment by e0ipso** [comment]
This was done, thanks for reporting!
