### ISSUE TITLE
Contenta no works

### ISSUE THREAD

**Issue by KathyLiz** [contentacms/contenta_jsonapi#324]
![image](https://user-images.githubusercontent.com/19628870/46550723-78faf980-c89b-11e8-9336-e8c2d6edbf13.png)
I trying to install contenta but have this problem :( please helpme

**Comment by e0ipso** [comment]
It seems that you are missing a PHP extension in your local. This is unrelated to Contenta CMS.

**Comment by e0ipso** [comment]
Can you confirm that `php -m` includes all the necessary extensions?

**Comment by e0ipso** [comment]
I'm closing this. I'm doing an issue clean-up.

Please request a re-open if you feel it's still a relevant issue.
