### ISSUE TITLE
Installation woes

### ISSUE THREAD

**Issue by ludo1960** [contentacms/contenta_jsonapi#325]
Hi Guys,

Thanks for all the effort you guys have put into this project, I can't wait to get to 'play' with it :~)

Installation problem:

My .env.local file has the following:

ACCOUNT_NAME=admin
ACCOUNT_PASS=admin

MYSQL_DATABASE=contenta-8
MYSQL_HOSTNAME=localhost
MYSQL_PORT=3306
MYSQL_USER=myuser
MYSQL_PASSWORD=mypassword

output from install#;

 EXECUTING  /var/aegir/platforms/contenta-8/vendor/drush/drush/drush site-install contenta_jsonapi --verbose --yes \
  --root=/var/aegir/platforms/contenta-8/web \
  --db-url=mysql://:[REDACTED]@:/ \
  --site-mail= \
  --account-mail= \
  --site-name= \
  --account-name= \
  --account-pass="[REDACTED]";

```
 [info] Undefined index: driver SqlBase.php:79
Error: Class 'Drush\Sql\Sql' not found in /var/aegir/platforms/contenta-8/vendor/drush/drush/src/Sql/SqlBase.php on line 81 #0 /var/aegir/platforms/contenta-8/vendor/drush/drush/src/Sql/SqlBase.php(64): Drush\Sql\SqlBase::getInstance(Array, Array)
#1 /var/aegir/platforms/contenta-8/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php(255): Drush\Sql\SqlBase::create(Array)
#2 /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php(43): Drush\Commands\core\SiteInstallCommands->validate(Object(Consolidation\AnnotatedCommand\CommandData))
#3 /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->callValidator(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/CommandProcessor.php(167): Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->validate(Object(Consolidation\AnnotatedCommand\CommandData))
#5 /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/CommandProcessor.php(150): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#6 /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(404): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#7 /var/aegir/platforms/contenta-8/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/aegir/platforms/contenta-8/vendor/symfony/console/Application.php(964): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/aegir/platforms/contenta-8/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/aegir/platforms/contenta-8/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/aegir/platforms/contenta-8/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/aegir/platforms/contenta-8/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\Runtime\Runtime->doRun(Array)
#13 /var/aegir/platforms/contenta-8/vendor/drush/drush/drush.php(66): Drush\Runtime\Runtime->run(Array)
#14 /var/aegir/platforms/contenta-8/vendor/drush/drush/drush(4): require('/var/aegir/plat...')
#15 {main}
Error: Class &#039;Drush\Sql\Sql&#039; not found in Drush\Sql\SqlBase::getInstance() (line 81 of /var/aegir/platforms/contenta-8/vendor/drush/drush/src/Sql/SqlBase.php).
 [error]  Drush command terminated abnormally due to an unrecoverable error. 
 ERROR  The Drupal installer failed to install Contenta CMS.
Script scripts/install-mysql.sh handling the install:with-mysql event returned with error code 3
```

I installed sqlite as per instructions so dont know what to try next?

Thanks again for all your work!

**Comment by e0ipso** [comment]
It seems that your `.env` and `.env.local` files are not being picked up.

Please make sure to follow the instructions in http://www.contentacms.org/#install

If you still have problems, paste here:

  - [ ] What php extensions do you have enabled (`php -m`)?
  - [ ] What command are you using to install Contenta CMS?
  - [ ] What is the contents of `.env`?
  - [ ] What is the contents of `.env.local`?
  - [ ] What command are you using to install Contenta CMS?

**Comment by ludo1960** [comment]
Thanks for getting back to me:

 **What php extensions do you have enabled (php -m)?**
ludo@aegir:~$ php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

**What command are you using to install Contenta CMS?:**

composer run-script install:with-mysql

**What is the contents of .env?:**

I don't have a .env file just a .env.loval content:

  MYSQL_DATABASE=contenta-8
  MYSQL_HOSTNAME=localhost
  MYSQL_PORT=3306
  MYSQL_USER=myuser
  MYSQL_PASSWORD=mypassword

What command are you using to install Contenta CMS?

composer run-script install:with-mysq

**Comment by e0ipso** [comment]
> I don't have a .env file just a .env.loval content:

This contradicts the installation instructions. Can you please try with that?

**Comment by ludo1960** [comment]
.env file:

  MYSQL_DATABASE=contenta-8
  MYSQL_HOSTNAME=localhost
  MYSQL_PORT=3306
  MYSQL_USER=ludo

.env.local file :+1: 

# Example .env file.
SITE_MAIL=admin@localhost
ACCOUNT_MAIL=admin@localhost
SITE_NAME='Contenta CMS Demo'
ACCOUNT_NAME=admin
MYSQL_DATABASE=contenta-8
MYSQL_HOSTNAME=localhost
MYSQL_PORT=3306
MYSQL_USER=ludo
MYSQL_PASSWORD=mypassword

output:

-----------------------------------------------
 Installing Contenta CMS for local usage 
-----------------------------------------------
 EXECUTING  /var/aegir/platforms/contenta-8/vendor/drush/drush/drush site-install contenta_jsonapi --verbose --yes \
  --root=/var/aegir/platforms/contenta-8/web \
  --db-url=mysql://ludo:[REDACTED]@localhost:3306/contenta-8 \
  --site-mail=admin@localhost \
  --account-mail=admin@localhost \
  --site-name=Contenta \
  --account-name=admin \
  --account-pass="[REDACTED]";


 [info] Executing: mysql --defaults-file=/tmp/drush_UlBak6 --database=contenta-8 --host=localhost --port=3306 --silent  < /tmp/drush_jMsPb2 > /dev/null

 // You are about to CREATE the 'contenta-8' database. Do you want to continue?:
 // yes.         
[info] Sites directory sites/default already exists - proceeding.
 [info] Executing: mysql --defaults-file=/tmp/drush_6UqDHe --database=contenta-8 --host=localhost --port=3306 --silent  < /tmp/drush_QE1Rva > /dev/null
 [info] Executing: mysql --defaults-file=/tmp/drush_XGtfbn --database=information_schema --host=localhost --port=3306 --silent  < /tmp/drush_GThpWi

In SiteInstallCommands.php line 357:
                                                                               
  [Exception]                                                                  
  Failed to create database: ERROR 1064 (42000) at line 1: You have an error   
  in your SQL syntax; check the manual that corresponds to your MariaDB serve  
  r version for the right syntax to use near '-8' at line 1                    
Exception trace:
 Drush\Commands\core\SiteInstallCommands->pre() at /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php:43
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->callValidator() at /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php:27
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->validate() at /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/CommandProcessor.php:167
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/CommandProcessor.php:150
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:404
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /var/aegir/platforms/contenta-8/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/aegir/platforms/contenta-8/vendor/symfony/console/Application.php:964
Symfony\Component\Console\Application->doRunCommand() at /var/aegir/platforms/contenta-8/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /var/aegir/platforms/contenta-8/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/aegir/platforms/contenta-8/vendor/drush/drush/src/Runtime/Runtime.php:112
 Drush\Runtime\Runtime->doRun() at /var/aegir/platforms/contenta-8/vendor/drush/drush/src/Runtime/Runtime.php:41
 Drush\Runtime\Runtime->run() at /var/aegir/platforms/contenta-8/vendor/drush/drush/drush.php:66
 require() at /var/aegir/platforms/contenta-8/vendor/drush/drush/drush:4

site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] 
[--notify [NOTIFY]] [--xh-link XH-LINK] [--] <command> [<profile>]...

 ERROR  The Drupal installer failed to install Contenta CMS.
Script scripts/install-mysql.sh handling the install:with-mysql event returned with error code 3
aegir@aegir:~/platfor

**Comment by ludo1960** [comment]
.env file:

MYSQL_DATABASE=contenta-8
MYSQL_HOSTNAME=localhost
MYSQL_PORT=3306
MYSQL_USER=ludo

.env.local file +1

Example .env file.
SITE_MAIL=admin@localhost
ACCOUNT_MAIL=admin@localhost
SITE_NAME='Contenta CMS Demo'
ACCOUNT_NAME=admin
MYSQL_DATABASE=contenta-8
MYSQL_HOSTNAME=localhost
MYSQL_PORT=3306
MYSQL_USER=ludo
MYSQL_PASSWORD=mypassword

output:

Installing Contenta CMS for local usage
EXECUTING /var/aegir/platforms/contenta-8/vendor/drush/drush/drush site-install contenta_jsonapi --verbose --yes 
--root=/var/aegir/platforms/contenta-8/web 
--db-url=mysql://ludo:[REDACTED]@localhost:3306/contenta-8 
--site-mail=admin@localhost 
--account-mail=admin@localhost 
--site-name=Contenta 
--account-name=admin 
--account-pass="[REDACTED]";

[info] Executing: mysql --defaults-file=/tmp/drush_UlBak6 --database=contenta-8 --host=localhost --port=3306 --silent < /tmp/drush_jMsPb2 > /dev/null

// You are about to CREATE the 'contenta-8' database. Do you want to continue?:
// yes.
[info] Sites directory sites/default already exists - proceeding.
[info] Executing: mysql --defaults-file=/tmp/drush_6UqDHe --database=contenta-8 --host=localhost --port=3306 --silent < /tmp/drush_QE1Rva > /dev/null
[info] Executing: mysql --defaults-file=/tmp/drush_XGtfbn --database=information_schema --host=localhost --port=3306 --silent < /tmp/drush_GThpWi

In SiteInstallCommands.php line 357:

[Exception]
Failed to create database: ERROR 1064 (42000) at line 1: You have an error
in your SQL syntax; check the manual that corresponds to your MariaDB serve
r version for the right syntax to use near '-8' at line 1
Exception trace:
Drush\Commands\core\SiteInstallCommands->pre() at /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php:43
Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->callValidator() at /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php:27
Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->validate() at /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/CommandProcessor.php:167
Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/CommandProcessor.php:150
Consolidation\AnnotatedCommand\CommandProcessor->process() at /var/aegir/platforms/contenta-8/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:404
Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /var/aegir/platforms/contenta-8/vendor/symfony/console/Command/Command.php:255
Symfony\Component\Console\Command\Command->run() at /var/aegir/platforms/contenta-8/vendor/symfony/console/Application.php:964
Symfony\Component\Console\Application->doRunCommand() at /var/aegir/platforms/contenta-8/vendor/symfony/console/Application.php:248
Symfony\Component\Console\Application->doRun() at /var/aegir/platforms/contenta-8/vendor/symfony/console/Application.php:148
Symfony\Component\Console\Application->run() at /var/aegir/platforms/contenta-8/vendor/drush/drush/src/Runtime/Runtime.php:112
Drush\Runtime\Runtime->doRun() at /var/aegir/platforms/contenta-8/vendor/drush/drush/src/Runtime/Runtime.php:41
Drush\Runtime\Runtime->run() at /var/aegir/platforms/contenta-8/vendor/drush/drush/drush.php:66
require() at /var/aegir/platforms/contenta-8/vendor/drush/drush/drush:4

site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon]
[--notify [NOTIFY]] [--xh-link XH-LINK] [--] []...

ERROR The Drupal installer failed to install Contenta CMS.
Script scripts/install-mysql.sh handling the install:with-mysql event returned with error code 3
aegir@aegir:~/platfor

**Comment by ludo1960** [comment]
mysql doesn't allow -(hyphens) in database names, so I changed contesta-8 to contesta and it worked first time!  Learn something every day, never knew that, sorry for bothering you, and thanks for help.
