### ISSUE TITLE
Libraries location

### ISSUE THREAD

**Issue by ludo1960** [contentacms/contenta_jsonapi#327]
Hi,

Status page says "Dropzonejs requires the dropzone.min.js library. Download it (https://github.com/enyo/dropzone) and place it in the libraries folder (/libraries)" so I downloaded it but dont find a libraries folder in contenta directory! I tried /libraries then /web/libraries without any luck, where is the libraries folder supposed to be?

**Comment by lrkwz** [comment]
See https://github.com/contentacms/contenta_docker/issues/28 and https://www.drupal.org/project/dropzonejs/issues/2871003

**Comment by e0ipso** [comment]
This seems to be handled elsewhere already. Closing.ç

Please request a re-open if this is indeed Contenta CMS specific.
