### ISSUE TITLE
How to download raw Contenta?

### ISSUE THREAD

**Issue by h-archer** [contentacms/contenta_jsonapi#331]
How can I get a copy of Contenta alone? I don't need any scripts that install a database or anything with it. I just need a raw copy of Contenta and I will install MariaDB and do the install and setup.

This Contenta distribution:
https://github.com/contentacms/contenta_jsonapi_project

… is broken. It gives 6 errors during installation. So that doesn't help!

Please let me know.

**Comment by h-archer** [comment]
All working now and thanks for this great piece of work ;) I just needed to apply two patches that you guys have made but have not yet been committed to this branch.

**Comment by e0ipso** [comment]
@hga77 I'm wondering. Which branch do you mean?

**Comment by e0ipso** [comment]
> … is broken. It gives 6 errors during installation. So that doesn't help!

Please create an issue in that project with error messages so we can help you there.
