### ISSUE TITLE
Quick installation fails because drush is not found

### ISSUE THREAD

**Issue by alverena** [contentacms/contenta_jsonapi#332]
During the quick installation, I've got an error: 

```
./scripts/install.sh: line 23: contenta/vendor/drush/drush/drush: No such file or directory
 **ERROR  Drush is required to install Contenta CMS. Please install Contenta CMS using Composer. See http://www.contentacms.org/#install**
Script scripts/install-sqlite.sh handling the install:with-sqlite event returned with error code 5
./contentacms-quick-installer.sh: line 32: drush: command not found
./contentacms-quick-installer.sh: line 33: drush: command not found
```

However, I'm actually installing Contenta with Composer, so the root of the issue is in something else.

**Comment by e0ipso** [comment]
Do you have global preferences for Composer on where to store installed binaries?

**Comment by alverena** [comment]
> Do you have global preferences for Composer on where to store installed binaries?

I have a freshly installed Composer with its default preferences. 

(And if any changes are required, that's definitely should be mentioned anywhere in the installation documentation. )

**Comment by e0ipso** [comment]
This does not seem to be a problem for others, so I'm leaning towards a composer configuration issue.

Can you try this on another computer?

**Comment by e0ipso** [comment]
I'm closing this. I'm doing an issue clean-up.

Please request a re-open if you feel it's still a relevant issue.

**Comment by alverena** [comment]
I've actually tried this on my workstation and on AWS server.

**Comment by mrleblanc101** [comment]
I'm also having this issue. Why is it searching drush 3 level deep ? It should be only 2 level deep ? 
```author/package``` and not ```author/package/???```

**Comment by e0ipso** [comment]
> Why is it searching drush 3 level deep ? It should be only 2 level deep ?
author/package and not author/package/???

You are correct. However if you look closely you'll notice that it's searching for: `<vendor-dir>/<author>/<package>/<binary-name>`.

**Comment by mrleblanc101** [comment]
Yes, my error. I found out right after but couldn't find the issue on github anymore.

Although, the installer still says vendor/drush/drush/drush ```No such file or directory```. The path is correct and i can cd into the folder, i also have the latest composer version (1.8).
Is this not Mac compatible ? Couldn't find any information about that.  

Otherwise I tried the contenta_docker repo which has very few information and does not work either.

**Comment by tostinni** [comment]
Hi, I had the exact same error using 3.x installer, the page https://www.contentacms.org/#install doesn't mention drush and locally I have drush 8.4.5 installed.
Is there any specific requirement to install contenta ?

```$ ./contentacms-quick-installer.sh
Do you wish to install Contenta CMS (y/n)? y
Great!
Where do you want to install it? (Ex: /var/www/contentacms) contenta
contenta
...
  - Copy [web-root]/profiles/README.txt from assets/scaffold/files/profiles.README.txt
  - Copy [web-root]/themes/README.txt from assets/scaffold/files/themes.README.txt
Class Drupal\Composer\Composer is not autoloadable, can not call post-update-cmd script
The Quick Install uses SQLite to install Contenta CMS. This is not suited for production sites.
> scripts/install-sqlite.sh 'contenta'
./scripts/install.sh: line 23: contenta/vendor/drush/drush/drush: No such file or directory
 ERROR  Drush is required to install Contenta CMS. Please install Contenta CMS using Composer. See http://www.contentacms.org/#install
Script scripts/install-sqlite.sh handling the install:with-sqlite event returned with error code 5
./contentacms-quick-installer.sh: line 31: cd: too many arguments
We could not find an applicable site for that command.                                                                                    [error]
Command runserver needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run  [error]
this command.
The drush command 'runserver 127.0.0.1:8888' could not be executed.                                                                       [error]
propal@pr-dev01:/opt/www $ drush --version
 Drush Version   :  8.4.5
```

Thanks
