### ISSUE TITLE
install fail on OSX

### ISSUE THREAD

**Issue by johnwbarrick** [contentacms/contenta_jsonapi#334]
// You are about to CREATE the 'contenta2' database. Do you want to continue?: 
 // yes.                                                                        

 [info] Sites directory sites/default already exists - proceeding.
 [info] Executing: mysql --defaults-file=/private/tmp/drush_ywx904 --database=contenta2 --host=localhost --port=3306 --silent -A < /private/tmp/drush_uNMFc7 > /dev/null
 [info] Executing: mysql --defaults-file=/private/tmp/drush_Izo5Vr --database=information_schema --host=localhost --port=3306 --silent -A < /private/tmp/drush_iEM58U

In SiteInstallCommands.php line 354:
                                                           
  [Exception]                                              
  Failed to create database: sh: mysql: command not found  
                                                           

Exception trace:
 Drush\Commands\core\SiteInstallCommands->pre() at /Users/[user.name]/Documents/mamp/contenta2/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php:43
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->callValidator() at /Users/[user.name]/Documents/mamp/contenta2/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php:27
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->validate() at /Users/[user.name]/Documents/mamp/contenta2/vendor/consolidation/annotated-command/src/CommandProcessor.php:167
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /Users/[user.name]/Documents/mamp/contenta2/vendor/consolidation/annotated-command/src/CommandProcessor.php:150
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /Users/[user.name]/Documents/mamp/contenta2/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:404
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /Users/[user.name]/Documents/mamp/contenta2/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /Users/[user.name]/Documents/mamp/contenta2/vendor/symfony/console/Application.php:964
 Symfony\Component\Console\Application->doRunCommand() at /Users/[user.name]/Documents/mamp/contenta2/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /Users/[user.name]/Documents/mamp/contenta2/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /Users/[user.name]/Documents/mamp/contenta2/vendor/drush/drush/src/Runtime/Runtime.php:112
 Drush\Runtime\Runtime->doRun() at /Users/[user.name]/Documents/mamp/contenta2/vendor/drush/drush/src/Runtime/Runtime.php:41
 Drush\Runtime\Runtime->run() at /Users/[user.name]/Documents/mamp/contenta2/vendor/drush/drush/drush.php:66
 require() at /Users/[user.name]/Documents/mamp/contenta2/vendor/drush/drush/drush:4

site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command> [<profile>]...

 ERROR  The Drupal installer failed to install Contenta CMS.
Script scripts/install-mysql.sh handling the install:with-mysql event returned with error code 3

**Comment by e0ipso** [comment]
` Failed to create database: sh: mysql: command not found`

This indicates that `mysql` is not installed in your local. Please try with `brew install mysql` or https://dev.mysql.com/doc/refman/5.5/en/osx-installation.html

If that does not fix the issue, please request a re-open.
