### ISSUE TITLE
Is contenta being actively maintained?

### ISSUE THREAD

**Issue by barkbyte** [contentacms/contenta_jsonapi#336]
I've seen several issues here that have gone unanswered for a few weeks.  I know the builders of this are probably mighty busy with other (paying) work, but attempting to test this on OSX I come up with numerous issues... the installer doesn't work and fails.  I've worked around that and managed to get drupal installed, then had an issue with where to put the dropzone.js library (I've put that in multiple /libraries folder and I'm still getting a warning it can't be found.  Then when I attempt to look at the sample content I'm getting a crash related to jsonapi_extras.

**Comment by e0ipso** [comment]
It is very maintained. However I'm on vacation.

I invite you to inspect the issues and help respond what you can. That way
the open source community is stronger.

**Comment by barkbyte** [comment]
...and the work is much appreciated.  My question was not a judgement... just wondering if things had moved on to another project.

**Comment by e0ipso** [comment]
No worries. I understand that. However the invitation to go through the
issue queue and help out still stands. ☺️

**Comment by e0ipso** [comment]
I hope that's clarified.
