### ISSUE TITLE
Installer script should remove $mytmpdir path from composer.json

### ISSUE THREAD

**Issue by tormi** [contentacms/contenta_jsonapi#34]
contentacms.sh deletes $mytmpdir (`rm -Rf $mytmpdir`), but it doesn't remove it's leftovers from composer.json:

```
        "contenta_jsonapi": {
            "type": "path",
            "url": "/tmp/tmp.rNrutuiEsy"
        }
```

**Comment by tormi** [comment]
@e0ipso, Happy Birthday and thank you for all the time an effort you have put into this !!! :beer: :birthday: :smile:

**Comment by dawehner** [comment]
Ah so you propose to do a ```git checkout``` afterwards? Do you want to file a PR?

**Comment by tormi** [comment]
No, never mind ;)
