### ISSUE TITLE
Install on postgresql

### ISSUE THREAD

**Issue by rfnbnkr** [contentacms/contenta_jsonapi#346]
Hi. Is there any way to install contentacms on postgresql?

**Comment by e0ipso** [comment]
Yes, there is nothing that precludes you from using postgresql. However there are not documented helpers for that. I'd recommend you to adapt the mysql installer script to use postgres. I'd be happy to merge that if you can submit a PR.

**Comment by e0ipso** [comment]
@rfnbnkr did you manage to do this? Would you mind opening a documentation PR to clarify the gotchas for that?

**Comment by e0ipso** [comment]
Please, request a re-open if this is not fixed.
