### ISSUE TITLE
OpenAPI warning after clean install

### ISSUE THREAD

**Issue by hyperfocus1337** [contentacms/contenta_jsonapi#352]
When opening `/admin/api` page after clean install I'm getting the following message:

```
Warning: No "type" specified at "/definitions/menu_link_content--menu_link_content/properties/data/properties/relationships". Automatically detected: "object"
```

What is it about? Safe to ignore?

**Comment by e0ipso** [comment]
This seems to be an issue with either https://www.drupal.org/project/schemata or https://www.drupal.org/project/openapi. Can you create a bug report to either one of these projects?

It is safe to ignore.
