### ISSUE TITLE
Unable to delete multiple field from content type node

### ISSUE THREAD

**Issue by psuplat** [contentacms/contenta_jsonapi#356]
I have a content type which contains the link field. The link field is set to unlimited and users can add as many as they wish. The problem is there is no option to delete a link, for example if user was to  accidentally click the "Add" button or wants to remove some old link.

**Comment by luksak** [comment]
In my opinion this is a Dupal Core issue. You have to empty the field to delete an item. Here is the corresponding issue on d.o: https://www.drupal.org/project/drupal/issues/1038316

**Comment by e0ipso** [comment]
Closing per comment above ☝🏼
