### ISSUE TITLE
Another go with contenta

### ISSUE THREAD

**Issue by ludo1960** [contentacms/contenta_jsonapi#364]
Hi guys,

Installed the latest and greatest contenta cms. now when I got to a recipe I get:
![image](https://user-images.githubusercontent.com/41955921/56956456-1ff6f980-6b3c-11e9-9489-e06533567786.png)

Is that what i'm supposed to see? should it not be a pretty picture! where am I going wrong this time? Desperate to try out the vue.js distro! Any news about a new maintainer?

**Comment by slattery** [comment]
I also need pointers to some contentacms walkthroughs.   Maybe the slack channel is the better place for us to ask?  Check out the #contenta channel on the [drupal slack](https://drupal.slack.com/).

**Comment by ludo1960** [comment]
Hey Mike,

I've made progress, use node.js to start a new project. I had contenta in var/www/contenta. I started a new node.js project in /var/nodejs/myproject then I moved the /var/www/contenta folder to /var/nodejs. changed the server path in my nginx config to the new path. Installed the contentajs into the PROJECT_ROUTE which is /var/nodejs/myproject and voila it all works!

________________________________
