### ISSUE TITLE
un able to update my packages on ubuntu server via composer in laravel application

### ISSUE THREAD

**Issue by isahlabbo** [contentacms/contenta_jsonapi#368]
mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 698359808) (tried to allocate 20480 bytes) in /usr/share/php/Composer/DependencyResolver/RuleSetGenerator.php on line 126

Fatal error: Out of memory (allocated 698359808) (tried to allocate 20480 bytes) in /usr/share/php/Composer/DependencyResolver/RuleSetGenerator.php on line 126

**Comment by djvilione** [comment]
Try: 

`COMPOSER_MEMORY_LIMIT=-1 composer update --with-dependencies;`

**Comment by isahlabbo** [comment]
I created swap file on the server and it works perfectly
