### ISSUE TITLE
Which Contenta branch to install?

### ISSUE THREAD

**Issue by h-archer** [contentacms/contenta_jsonapi#370]
Please recommend which branch to install. 

The installation docs [here](https://www.contentacms.org/) have the following:

`php -r "readfile('https://raw.githubusercontent.com/contentacms/contenta_jsonapi_project/8.x-2.x/scripts/download.sh');" > download-contentacms.sh`

This targets the 8.x-2.x branch. But there is another newer branch, 8.x-3.x.

Should I install the latest branch?

**Comment by e0ipso** [comment]
Note that this targets `8.x-2.x` in the `contentacms/contenta_jsonapi_project` repository. Not `contentacms/contenta_jsonapi`.
