### ISSUE TITLE
Schemata 8.x.1.0-beta1 breaks contenta

### ISSUE THREAD

**Issue by ludo1960** [contentacms/contenta_jsonapi#376]
As the title says, updating the schemata module breaks contenta, didn't have db logging on so dont have any details. Stick with Schemata alpha7

**Comment by apotek** [comment]
Was this the error you got? 

```
Fatal error: Uncaught Error: Class 'Drupal\Core\Routing\RouteObjectInterface' not found in ..../web/modules/contrib/schemata/src/Routing/Routes.php:108
```

If it is, it's the same error I have when trying to run latest contenta_jsonapi against Drupal 8. The RouteObjectInterface does not exist in Drupal 8. 

I ended up pinning schemata to alpha7 too. 

^^ Maintainers... Am I missing a note somewhere about which version of contenta_jsonapi breaks compatibility with Drupal 8?
