### ISSUE TITLE
Design website layout

### ISSUE THREAD

**Issue by khaldoonmasud** [contentacms/contenta_jsonapi#381]
What's the best way to design website layout and how to get the content. For example I have header menus, footer menus, content body, left side blocks and right side blocks. Do I make multiple data request on page load to get all the components? 
/jsonapi/blocks
/jsonsapi/nodes
/jsonapi/menus
How can I create the entire page with one json request? Do I need to use nodejs for first page load?

**Comment by fiasst** [comment]
Hey Khaldoon, what a small Internet ;) Hope you're enjoying SD!

Marc Hudson (Encore)

**Comment by khaldoonmasud** [comment]
> Hey Khaldoon, what a small Internet ;) Hope you're enjoying SD!
> 
> Marc Hudson (Encore)

Hey Marc, Haha I can also recognize you without (Encore). When you are working on same the technologies, it's very likely that we run into each other online. :) SD is great. I hope you are doing well.
