### ISSUE TITLE
[Feature Request] Add Decoupled Kit to Contenta CMS

### ISSUE THREAD

**Issue by renatog-cit** [contentacms/contenta_jsonapi#394]
Hello Conteta Team, how are you?

Congrats on the project! Contenta is amazing!

What do you think about include [Decoupled Kit](https://www.drupal.org/project/decoupled_kit) by default in ContentaCMS?

https://www.drupal.org/project/decoupled_kit

Decoupled Kit is a new project with new capabilities for decoupled drupal and creates routes with JSON output, for example:

```
Block
Get blocks for current page.

Menu
Get menu data.

Taxonomy
Get taxonomy tree.

Sitemap
Get sitemap using decoupled menu and decoupled taxonomy.

Breadcrumb
Get breadcrumbs for current page.

Metatag
Metatag module integration. Get data for current page.

Webform
Webform module integration. Get data for current page. Recommend use Webform rest module.

Redirect
Redirect module integration. Get data for current page.```

![img](https://user-images.githubusercontent.com/36484033/72523398-75944300-383e-11ea-93f5-5a1d438671da.png)

It's only a suggestion.

Thank you so much!

Best,

**Comment by e0ipso** [comment]
Hello! Thanks for the work!

While I am not sure enabling this for all Contenta installs is the best path forward, I do see a lot of value in having it present as an optional module.

Can you make a PR to create a plugin for it like the ones in https://github.com/contentacms/contenta_jsonapi/tree/8.x-3.x/src/Plugin/Contenta/OptionalModule?

Thanks!

**Comment by renatog-cit** [comment]
Okay, I'll work on that.

Thank you so much
