### ISSUE TITLE
Admin-Toolbar-Version

### ISSUE THREAD

**Issue by attus74** [contentacms/contenta_jsonapi#395]
Hi, even the most recent version of Contenta requires ^1.23 of module Admin Toolbar.
However, the version 1 is obsolete, and Drupal sends a notification again and again that this module shall be upgraded. 
Is there any reason why you don't let this module to be upgraded?

**Comment by e0ipso** [comment]
@attus74 I didn't realize version 2 is out. Feel free to update your site!
