### ISSUE TITLE
Drupal 9 readyness

### ISSUE THREAD

**Issue by BrianGilbert** [contentacms/contenta_jsonapi#397]
In the interest of keeping customers sites up to date core wise just starting this ticket to see if there are known issues blocking the D9 upgrade of a contenta site?

**Comment by BrianGilbert** [comment]
Going through the composer files dependencies I've found the following with regard to 9.0 compatibility.

- admin_toolbar: use version 2.2
- contentajs: created an issue https://www.drupal.org/project/contentajs/issues/3122453
- consumer_image_styles: created an issue https://www.drupal.org/project/consumer_image_styles/issues/3122456
- decoupled_router: https://www.drupal.org/project/decoupled_router/issues/3111732
- environment_indicator https://www.drupal.org/project/environment_indicator/issues/3042790
- image_widget_crop: use version 2.x-dev 
- inline_entity_form: use 1.x-dev 
- jsonapi_boost: created an issue https://www.drupal.org/project/jsonapi_boost/issues/3122457
- jsonapi_extras: https://www.drupal.org/project/jsonapi_extras/issues/3069220
- jsonrpc: created an issue https://www.drupal.org/project/jsonrpc/issues/3122454
- material_admin: suggest adminimal theme as it's less buggy https://www.drupal.org/project/adminimal_theme/issues/3075752
- openapi: use 2.x-dev
- openapi_jsonapi: use 2.x-dev
- openapi_ui: use 1.x-dev
- openapi_ui_redoc: use 1.x-dev
- schemata_json_schema: scemata needs a release built https://www.drupal.org/node/2772573/commits
- simple_oauth: use version 4.4
- subrequests: https://www.drupal.org/project/subrequests/issues/3122455
- video_embed_field: use version 2.3
- warmer: open issue https://www.drupal.org/project/warmer/issues/3074742

**Comment by lukewhitmore** [comment]
> Going through the composer files dependencies I've found the following with regard to 9.0 compatibility.
> 
> * admin_toolbar: use version 2.2
> * **[needs review]** contentajs: created an issue https://www.drupal.org/project/contentajs/issues/3122453
> * **[fixed]** consumer_image_styles: created an issue https://www.drupal.org/project/consumer_image_styles/issues/3122456
> * **[fixed]** decoupled_router: https://www.drupal.org/project/decoupled_router/issues/3111732
> * **[fixed]** environment_indicator https://www.drupal.org/project/environment_indicator/issues/3042790
> * image_widget_crop: use version 2.x-dev
> * inline_entity_form: use 1.x-dev
> * **[needs review]** jsonapi_boost: created an issue https://www.drupal.org/project/jsonapi_boost/issues/3122457
> * **[fixed]** jsonapi_extras: https://www.drupal.org/project/jsonapi_extras/issues/3069220
> * **[needs review]** jsonrpc: created an issue https://www.drupal.org/project/jsonrpc/issues/3122454
> * material_admin: suggest adminimal theme as it's less buggy https://www.drupal.org/project/adminimal_theme/issues/3075752
> * openapi: use 2.x-dev
> * openapi_jsonapi: use 2.x-dev
> * openapi_ui: use 1.x-dev
> * openapi_ui_redoc: use 1.x-dev
> * **[fixed]** schemata_json_schema: scemata needs a release built https://www.drupal.org/node/2772573/commits
> * simple_oauth: use version 4.4
> * **[fixed]** subrequests: https://www.drupal.org/project/subrequests/issues/3122455
> * video_embed_field: use version 2.3
> * **[fixed]*warmer: open issue https://www.drupal.org/project/warmer/issues/3074742

**Comment by calvinte** [comment]
😬 can't wait 🚀

**Comment by msreis66** [comment]
Created a new pull request to change the deprecated funcion drupal_set_message to \Drupal::messenger()->addMessage() on module contenta_enhancements https://github.com/contentacms/contenta_jsonapi/pull/410.

While it has not been merged there's a temporary patch to apply the changes https://gist.github.com/msreis66/3caab217ba9a54609d0caa91a84e553c. 

Cc @e0ipso .
