### ISSUE TITLE
Install fails - Unable to install modules: module 'entity_reference' is obsolete.

### ISSUE THREAD

**Issue by christoph-theunert** [contentacms/contenta_jsonapi#413]
When trying to install the current D9.3 and running `composer run-script install:with-mysql` I get this error 
`[Drupal\Core\Extension\Exception\ObsoleteExtensionException]       
  Unable to install modules: module 'entity_reference' is obsolete.`

and installation fails.

See [this issue](https://www.drupal.org/project/drupal/issues/3253622)

Don't know how to solve it.

**Comment by brocakun** [comment]
Hey, @christoph-theunert we fixed this by removing _entity_reference: 0_ on the config/sync/core.extension.yml file and applying it as a patch.

Hope this can help you!

**Comment by e0ipso** [comment]
This was fixed. Thanks for the report!
