### ISSUE TITLE
Drupal 9.4 breaks configuration import

### ISSUE THREAD

**Issue by jaysonegarcia** [contentacms/contenta_jsonapi#418]
Hi mateu,

When I tried to import the config/sync, I encountered this error:
Unable to uninstall the <em class="placeholder">MySQL</em> module because: The module 'MySQL' is providing the database driver 'mysql'

The **resolution** has to be performed manually by adding the **mysql: 0** in core.extension.yml under **profile/contrib/contenta_jsonapi/config/sync**

**Comment by ninjainvenio** [comment]
yes, I also get the same error but contenta is not updated yet.
