### ISSUE TITLE
Test OpenAPI as a replacement for Docson

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#47]
This is currently blocked by Schemata.

**Comment by dawehner** [comment]
Sounds really good!

**Comment by tedbow** [comment]
I think the latest dev version of Schemata  should work I think. But should try to see if we can get the maintainer to do a release.

**Comment by dawehner** [comment]
@tedbow For comment we still needed to apply the RTBC patch against schemata

**Comment by wimleers** [comment]
https://github.com/contentacms/contenta_jsonapi/commit/15adb293711351dbc5c8f812ac5923055601a707 already did this?

**Comment by dawehner** [comment]
We wanted to test it for a while before we really announce it :)

Wim Leers <notifications@github.com> schrieb am Mi., 21. Juni 2017 um
10:00 Uhr:

**Comment by wimleers** [comment]
👍

**Comment by e0ipso** [comment]
This was done. We are currently using Open API.
