### ISSUE TITLE
Auto-deploy Contenta CMS to a publicly accessible site

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#48]
We have something going on with CircleCI and Pantheon, but it's a bit abandoned / disfunctional at the moment.

**Comment by dawehner** [comment]
I'll try to get it running again. Is it okay that it runs under some
different domain?

**Comment by dawehner** [comment]
@e0ipso Is this solved now?

**Comment by e0ipso** [comment]
Yes!
