### ISSUE TITLE
Generate an oauth client by default

### ISSUE THREAD

**Issue by dawehner** [contentacms/contenta_jsonapi#56]
See https://github.com/acquia/reservoir/blob/8.x-1.x/reservoir.install#L31

**Comment by chris-hamper** [comment]
I'll take on implementing this

**Comment by dawehner** [comment]
Nice, thank you a lot already!

chris-hamper <notifications@github.com> schrieb am Di., 27. Juni 2017 um
12:43 Uhr:

**Comment by cjgratacos** [comment]
@chris-hamper I had my eye on this issue. Awesome, I am really interested in the PR.

**Comment by e0ipso** [comment]
This has become stale.
