### ISSUE TITLE
Add an developer and a editor role

### ISSUE THREAD

**Issue by dawehner** [contentacms/contenta_jsonapi#57]
It would be nice to have a role for editors as well as one role for developers.

What kind of permissions should each of those actually have?

**Comment by dawehner** [comment]
Potential follow up generate some example users

**Comment by e0ipso** [comment]
I think it would be a good idea to converge on the same roles _Reservoir_ creates with the same permissions (we'll have more than them because there are more features to grant permissions to).

### Roles list
  - [x] Anonymous user
  - [x] Authenticated user
  - [x] Content administrator
  - [x] Client developer

**Comment by e0ipso** [comment]
This was addressed by 076222c1db809b9bdb82386e74c2e24510ad4891. I'm leaving this open in case you want to change the permissions set. I got the permission list from Reservoir.

**Comment by wimleers** [comment]
- You committed `uuid`s as well in the config. You don't want that :)
- Interesting that you're also adding actions. Can you explain why?
- Finally: do you _like_ the user role labels? _Content administrator_ and _Client developer_? Would you have chosen different role labels?

**Comment by dawehner** [comment]
> You committed uuids as well in the config. You don't want that :)

As someone who is using Drupal in the wild, I can say the patch provided by alexpott in https://www.drupal.org/node/2788777 totally makes this possible. It allows you to use ```drush cex``` with install profiles basically. 

> Interesting that you're also adding actions. Can you explain why?

This happens when you drush cex :) To be honest though we REALLY don't need them IMHO.

> Finally: do you like the user role labels? Content administrator and Client developer? Would you have chosen different role labels?

For me at least "administrator" feels like something with more capabilities. What about "content editor"?

**Comment by e0ipso** [comment]
> Finally: do you like the user role labels? Content administrator and Client developer? Would you have chosen different role labels?

I just reused what it was there. I don't care all that much, i figured that we can change them later. :-P

> You committed uuids as well in the config. You don't want that :)

What Daniel said.

> Interesting that you're also adding actions. Can you explain why?

We want to have a simple config workflow (it was Alex's only direction). What we want to do is:
  - Click around.
  - `drush cex`
  - Commit.

Anything more complex than can lead to debugging configuration sets. Not a fun place to be. If that brings in default config that will be created anyways on install, I'm fine with the tradeoff.

**Comment by wimleers** [comment]
> For me at least "administrator" feels like something with more capabilities. What about "content editor"?

But "Content editor" implies more limited capabilities: they can edit content, maybe create new content … but not also publish and manage _all_ content.
That's why I first went with "Content manager". At some point I changed it to "Content administrator".

**Comment by e0ipso** [comment]
We did this already.
