### ISSUE TITLE
[plan] Road towards a release

### ISSUE THREAD

**Issue by dawehner** [contentacms/contenta_jsonapi#58]
What do we want to have before a release?

Note: A release adds a lot of momentum, there is some magical force involved

**Comment by dawehner** [comment]
It could be an alpha/beta release maybe?

**Comment by e0ipso** [comment]
I want an alpha for my presentation in Barcelona. I think that the front page theming and the quick overview is blocking that.

Shall we add issues to fix them?

**Comment by dawehner** [comment]
Issues are never a bad idea :p

**Comment by e0ipso** [comment]
We had a release!
