### ISSUE TITLE
Regroup the admin ui

### ISSUE THREAD

**Issue by dawehner** [contentacms/contenta_jsonapi#59]
As we can learn from reservoir, we can totally improve the experience by providing a more focused admin UI.

* Make content modelling a first class citizen
* Make UI developers tasks a first class citizien, aka. API documentation, OAuth client, Oauth tokens etc.

**Comment by ckrina** [comment]
Totally agree. Identifying first the main tasks for each role (#57) would help a lot here.

**Comment by e0ipso** [comment]
@ckrina this is now unblocked, as #57 was fixed.

**Comment by briancwald** [comment]
What do you need me to do? Happy to focus material admin efforts on anything that improved authoring.

**Comment by e0ipso** [comment]
This was done.
