### ISSUE TITLE
Create a logo / brand

### ISSUE THREAD

**Issue by dawehner** [contentacms/contenta_jsonapi#7]

**Comment by theodorosploumis** [comment]
Hi, is this issue still active? I see a logo on the Org page. 
I could create some proposals if you like. 

Coming from the Drupal world but I like creating design assets for Drupal projects. Thanks.

**Comment by dawehner** [comment]
I know that https://www.drupal.org/u/ckrina worked on some logo suggestions @e0ipso can you ping them?

**Comment by dawehner** [comment]
@theodorosploumis Welcome! I'm sure there is room for colaboration/ other stuff to work on :)

**Comment by theodorosploumis** [comment]
In any case I am watching this project from the "Drupal" side. ;-)

**Comment by dawehner** [comment]
@theodorosploumis You are more than welcomed  to join the ```#contenta``` room in the drupal slack

**Comment by e0ipso** [comment]
I don't know if this counts as branding, but I am tempted to use `lolcat` in all the command line output screenshots.

Example:
![web zsh 2017-06-02 10-20-49](https://cloud.githubusercontent.com/assets/1140906/26717368/6e7f1400-477d-11e7-9064-1e83f23269ca.png)

![contenta zsh 2017-06-02 10-24-59](https://cloud.githubusercontent.com/assets/1140906/26717450/bdee3d68-477d-11e7-9baa-02e87f3d8428.png)

Please vote.

**Comment by dawehner** [comment]
Lol, well ensure that Travis/circle CI output is readable.to be honest confveve is the way more powerful alternative tool.

**Comment by e0ipso** [comment]
Yay @ckrina! Thanks!
