### ISSUE TITLE
"Not Allowed." displayed when logging in to the site

### ISSUE THREAD

**Issue by chris-hamper** [contentacms/contenta_jsonapi#76]
When logging into the site using the form at /user, the browser displays an almost-empty page with just the message "Not Allowed."

This is likely due to the CORS bug described in https://www.drupal.org/node/2853201

@dawehner suggested applying: https://github.com/asm89/stack-cors/commit/6daf5757971173b79ddabbd755d59d333c278f42.patch
to fix this.

**Comment by dawehner** [comment]
Thank you for reporting @chris-hamper 
We have solved the issue with the PR, so I'm closing the issue now.
