### ISSUE TITLE
readme.md should have an introductory blurb explaining what Contenta is

### ISSUE THREAD

**Issue by davidhwang** [contentacms/contenta_jsonapi#78]
Let's put a brief explanatory blurb at the top of the readme that describes what Contenta is, and what it does (and maybe why you should use it?)

**Comment by e0ipso** [comment]
@davidhwang maybe some extract from the tl;dr in https://medium.com/@mateu.aguilo.bosch/contenta-makes-your-content-happy-6f76bbe0cdae?

**Comment by davidhwang** [comment]
Here's a try: https://github.com/contentacms/contenta_jsonapi/pull/79
