### ISSUE TITLE
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2870904-22.patch

### ISSUE THREAD

**Issue by jakubsuchy** [contentacms/contenta_jsonapi#82]
- Installing drupal/simple_oauth (2.0.0-rc2) Loading from cache
  - Installing drupal/schemata (dev-1.x 99c723d) Cloning 99c723ddd4 from cache
  - Applying patches for drupal/schemata
    https://www.drupal.org/files/issues/2870904-22.patch (https://www.drupal.org/files/issues/2870904-22.patch)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2870904-22.patch

**Comment by jakubsuchy** [comment]
I've tried clearing cache and did not help. Here is a similar issue: https://github.com/acquia/reservoir/issues/42

**Comment by e0ipso** [comment]
Closed by #83.

@jakubsuchy can you confirm this issue is fixed?

**Comment by cmoeser** [comment]
Also seeing this when trying to install with composer
![screen-shot](https://user-images.githubusercontent.com/2686223/43460872-ede2f070-949f-11e8-957e-4b0dba83b365.jpg)
