### ISSUE TITLE
Create a module that will ignore the path field on entities when routing in Drupal

### ISSUE THREAD

**Issue by justafish** [contentacms/contenta_jsonapi#85]
Following up from the routing discussion in Slack, we would like a module that prevents Drupal from using the contents of the path field for routing. The path field will provide the routes that front-end consumers use, and this prevents conflicts from trying to overlay a should-be-separate routing system on top of Drupal's routing system, without losing the benefits of the path module (i.e. pathauto integration)

The path field currently checks for conflicts in values with other path fields, this functionality should be maintained.

**Comment by dawehner** [comment]
This module exists now in the form of [snail](https://www.drupal.org/project/snail) module.
