### ISSUE TITLE
Have JSON API Extras return the new path value when there is a redirect

### ISSUE THREAD

**Issue by justafish** [contentacms/contenta_jsonapi#86]
Following up from the routing discussion in Slack, JSON:API needs to return the value of the new path of some content when it's slug/path has been changed.

It doesn't need to return the contents of the node at the new location, just the value of the new path so a redirect can be sent to the user.

**Comment by e0ipso** [comment]
Thanks for opening this @justafish!

After thinking on how to best implement this I realized that one significant complication is that you have to check for uniqueness when you add a new slug.

That needs to be ensured not only for the currently available slugs across all the entity types, but also across all revisions on all entities on all entity types.

EntityQuery does not provide such querying capabilities. So it could be worth adding `redirect` integration when a slug changes.

Ideas?

**Comment by dawehner** [comment]
When I started to work on that, I realized this is indeed a problem. I think the way to go would be to leverage the KV store to continuesly store every slug we ever had.

**Comment by e0ipso** [comment]
> I think the way to go would be to leverage the KV store to continuesly store every slug we ever had.

That's a good way to go. The requirements for that would be:

  - The storage is persistent and not clearable (unless explicitly)
  - The storage is readable/writable across multiple webheads.

Does that impact viability on this solution?

**Comment by dawehner** [comment]
> The storage is persistent and not clearable (unless explicitly)

That is exactly what a KV is about, unlike cache for example. 

> The storage is readable/writable across multiple webheads.

This is the same for a KV store. Well theoretically you could mess it up on your implementation, but at least the default (DB) automatically ensures that.

**Comment by e0ipso** [comment]
@dawehner great! Is this the same that the redirect module will be doing? Should we have this piece re-usable for them as well?

**Comment by dawehner** [comment]
Well redirect uses entities to store redirects. This would be another
option we could use as well. I could imagine this is actually better, as
you can somehow deal with revisons/translations etc., but I'd have to have
a deeper dive into how redirect actually works.

Mateu Aguiló Bosch <notifications@github.com> schrieb am Mo., 3. Juli 2017
um 16:28 Uhr:

**Comment by e0ipso** [comment]
This was fixed with the `decoupled_router` module.
