### ISSUE TITLE
Extremely slow installation due to 'recipes_magazin__images_url' migration

### ISSUE THREAD

**Issue by boztek** [contentacms/contenta_jsonapi#89]
I understand this is a known issue.

In recipes_magazin.install there are multiple migrations that run during an installation. One of them is 'recipes_magazin__images_url', which I'm told downloads many images from the web.

The result is that without this migration, on a good day, a "rebuild" using scripts/development/build-contenta_jsonapi.sh and a warm composer cache etc. takes approximately 2 minutes, with about 15 seconds of that being the Drupal install. With that one migration added the Drupal installation takes at least an extra 6+ minutes, meaning a build takes from 7 to sometimes over 10 minutes depending on composer cache, or xdebug is enabled etc.

More of a serious problem for contributors but due to the lack of feedback also an issue for users going forward as it can appear frozen.

**Comment by dawehner** [comment]
I totally agree that this is a huge problem! Do you think https://github.com/contentacms/contenta_jsonapi/issues/91 would solve the problem?

**Comment by boztek** [comment]
While that looks like it would make sense for end users of the distro, isn't it reasonable to provide distro developers a reliable way to build and test changes without waiting 10mins? At the very least a flag to turn the migration off for distro developers or perhaps a way to cache those assets for rebuilds.

**Comment by dawehner** [comment]
I more than agree that we should speed that up.

I think using some placeholder by default and then fetching the images
later could work.

**Comment by e0ipso** [comment]
This was fixed. The images are now bundled with the repo.
