### ISSUE TITLE
Theme the installer?

### ISSUE THREAD

**Issue by dawehner** [contentacms/contenta_jsonapi#9]
Should we theme the installer maybe?

**Comment by e0ipso** [comment]
That was something I brought up with @ckrina earlier today. I'd like her to asses how important it would be.

I like the idea, it conveys the deep care we have for the project.

**Comment by ckrina** [comment]
Assuming installer will be one of the first project pages people will be in contact with, I would vote for theming it, yes.

**Comment by wimleers** [comment]
We've been thinking about this also for https://github.com/acquia/reservoir.

**Comment by dawehner** [comment]
If we theme the installer we should use a materialized style, IMHO. It fits into the environment for the other parts.

I personally though believe that using command line is the way to go for setting up Drupal given that ANY frontend technology these days is doing that. We already let people use composer to use it in the first place. Switching to the browser would be a bit of a context switch to be honest.

Maybe we could have something like:

```
contenta install --with-content
contenta install --without-content
```

It could allow you to set DB credentials, but by default use sqlite, much like our 100% automated installer.

**Comment by joaogarin** [comment]
my vote for theming installer : definitely :+1: :+1: !! 
I will try to sketch something for this during these next days
