### ISSUE TITLE
Implicit node dependency

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#90]
## Problem

At the moment we are executing `node install` as [part of the `create-project` composer command](https://github.com/contentacms/contenta_jsonapi_project/blob/8.x-1.x/scripts/composer/ScriptHandler.php#L116) in `contenta_jsonapi_demo`.

If we combine that with the [`package.json`](https://github.com/contentacms/contenta_jsonapi/blob/8.x-1.x/package.json) in `contenta_jsonapi` we have that the Nigthwatch testing environment is installed in _production mode_.

----

## Suggested solution
  - [ ] Convert the `dependencies` in [`package.json`](https://github.com/contentacms/contenta_jsonapi/blob/8.x-1.x/package.json) to `devDependencies`.
  - [ ] ~Make [the `create-project` composer command](https://github.com/contentacms/contenta_jsonapi_project/blob/8.x-1.x/scripts/composer/ScriptHandler.php#L116) run `npm install --production`.~ Remove the command in ScriptHandler.php that runs npm install
  - [x] Make sure the `.travis` deployer installs the devDependencies to run tests.

**Comment by justafish** [comment]
Marked off the 3rd item as travis already installs our dependencies.

npm is currently **only used for testing**, so we shouldn't be running this with the composer install at all. In fact, we don't even use npm, we use yarn :) Installation instructions for that are in https://github.com/contentacms/contenta_jsonapi#testing - I've updated the second task on the list to reflect this

**Comment by dawehner** [comment]
> npm is currently *only used for testing*, so we shouldn't be running this
with the composer install at all. In fact, we don't even use npm, we use
yarn :) Installation instructions for that are in
https://github.com/contentacms/contenta_jsonapi#testing - I've crossed out
the second item on the list

I do agree with that. This is currently in there inherited from drupal
create-project ... because well, it is potentially quite useful, and will
be for actual sites. Just imagine that they will probably use package.json
to deal with their own dependencies. Well, and given it would be actual
useful for real sites to leave it in, maybe we should do that? I guess
ideally we would expand it to check whether the system has yarn installed
and use that instead.

Given that I think making it a dev dependency is the right thing.

**Comment by e0ipso** [comment]
I think that there is merit to keep `npm install --production` (or `yarn` if you will) as part of the build process. Moving the testing stuff to the `devDependencies` will fix the current problem *and* the future problem without requiring additional work.

**Comment by e0ipso** [comment]
Decision pending:

  * Vote ❤️  for: _I agree that `node` is just for testing and we should not run `npm install --production` when installing via composer since we don't have anything to install._
  * Vote 🎉  for: _I agree that `node` is too useful for real projects so we should run `npm install --production` when installing via composer. This will be helpful for sites that use Contenta as a starter kit._

**Comment by dawehner** [comment]
One thing to keep in mind, we are executing npm install inside the ```profiles/contenta_jsonapi``` folder, a folder you would not touch when you work on a real site.

**Comment by e0ipso** [comment]
@dawehner well there is the case that you follow @dawehner's best practices and treat your site as a distribution based on Contenta, right?

But you are correct, that seems to be still rather unusual.

**Comment by e0ipso** [comment]
@dawehner yeah, that's true. I did not get it initially when @justafish brought that point up. I thought we were executing in the root.

I guess there's still value to discuss if we want to execute `npm install --production` in the root. But that's a different issue.

**Comment by dawehner** [comment]
@e0ipso So given that, you agree we should remove it?

**Comment by e0ipso** [comment]
> @e0ipso So given that, you agree we should remove it?

👍 YES. (sorry I wasn't clearer above)

**Comment by justafish** [comment]
https://github.com/contentacms/contenta_jsonapi_project/pull/3

**Comment by dawehner** [comment]
The PR is merged now
