### ISSUE TITLE
Create GitHub releases

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#91]
To speed up the installation process it would be nice to have a build that we could leverage [GitHub releases](https://github.com/blog/1547-release-your-software).

The idea is that for each merge to master (we should all use squashed commits), we should have a ZIP file with the result of `composer-create`. There is currently a task in Travis that builds the site for testing purposes. We should be able to leverage a lot of that logic to create the build asset. Then an auto-release with the build asset should be deployed by travis in GitHub.

**Comment by dawehner** [comment]
One thing we could discuss is whether we should bundle up the images for
the default_content migration in that ZIP file or not.

I guess this would have solved the speed problem for boztek

**Comment by cjgratacos** [comment]
I am going to take this issue.

**Comment by cjgratacos** [comment]
Going to also investigate on Travis CI github issue creator. With this, when a build fails and an artifact doesn't get promoted and a Github issue gets created for investigating.

**Comment by cjgratacos** [comment]
@e0ipso you mean zip the `composer create-project ...` result?

**Comment by e0ipso** [comment]
@cjgratacos yes. Zip alm the files that are needed to run drush site-install

**Comment by cjgratacos** [comment]
Closing. Issue was attended at #108
