### ISSUE TITLE
RealWorld backend..

### ISSUE THREAD

**Issue by spoetnik** [contentacms/contenta_jsonapi#95]
Would it be an idea to use Contenta as a RealWorld backend?
https://github.com/gothinkster/realworld

This would be a great promotion for Drupal as an API backend.

**Comment by e0ipso** [comment]
I think this is a cool idea! We're not there yet, but we could have a version of Contenta that does that.

**Comment by dawehner** [comment]
It would be indeed a really great idea! Sadly there is one major showstopper: RealWorld has a spec for the API, see https://github.com/gothinkster/realworld/blob/master/api/README.md which couldn't be achieved neither with rest in core, nor JSONAPI.

One could still develop custom rest resource plugins to achieve that. Maybe this would be then worth giving a try.

**Comment by e0ipso** [comment]
Closing for now. Maybe in the future we can explore the possibilities. When I said _we could have a version of Contenta that does that_ I had not read the API requirements. Given those, I don't think this is an effort that we are ready to take on at this point.
