### ISSUE TITLE
Warning: chmod(): Operation failed: No such file or directory in League\OAuth2\Server\CryptKey->__construct() (line 51 of /home/arif/contenta/demo/vendor/league/oauth2-server/src/CryptKey.php).

### ISSUE THREAD

**Issue by arifkhn46** [contentacms/contenta_jsonapi#96]
After installation I got following warning :

Warning: chmod(): Operation failed: No such file or directory in League\OAuth2\Server\CryptKey->__construct() (line 51 of /home/arif/contenta/demo/vendor/league/oauth2-server/src/CryptKey.php).

![warning-on-installation](https://user-images.githubusercontent.com/12694008/27767692-e4bb10ae-5f1c-11e7-9ec1-4b51375f694e.png)

**Comment by dawehner** [comment]
Thank you for reporting this issue. https://github.com/contentacms/contenta_jsonapi/issues/88 is a duplicate with an idea how to fix it.

**Comment by cjgratacos** [comment]
@dawehner can we attach the image to the #88 issue?, it would be a great reference, just for tracking purposes.

**Comment by dawehner** [comment]
@e0ipso posted a new RC of simple_oauth which fixes this particular problem, yeah!!
