### ISSUE TITLE
Grant permission to anonymous to 'access user profiles'

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#98]
We want to be able to access author information as an anonymous user.

**Comment by TuWebO** [comment]
Hi @e0ipso, 
do you mean having (in the profile configuration) **View user information** permission granted by default for anonymous users? If so, this will also needs to be applied to authenticathed users?

FYI
This permission name has changed the "title" to "View user information" (key remains the same), see commit at:
[http://cgit.drupalcode.org/drupal/commit/?id=b96e823](http://cgit.drupalcode.org/drupal/commit/?id=b96e823)

**Comment by e0ipso** [comment]
@TuWebO yes. It would be helpful to have it in both roles. This should go into the `recipes_magazin_contenta` module so it can be uninstalled when the default content is yanked.

**Comment by TuWebO** [comment]
Thanks @e0ipso,
I'll try to help out.

**Comment by TuWebO** [comment]
Starting to work in this branch
https://github.com/TuWebO/contenta_jsonapi/tree/fb-recipes-magazin-contenta-install

**Comment by e0ipso** [comment]
Great!
